### PR TITLE
Fix Java Serialization issue on mapWithUpdating

### LINKED ISSUE #671: Sinks.mapWithUpdating fails with java.io.NotSerializableException
[AbstractEntryProcessor](https://github.com/hazelcast/hazelcast-jet/blob/5f8e59640e9536123e4838a100044b25804b788d/hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java#L105) in `HazelcastWriters.updateMapP` forces Java serialization on entries.

```
at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[na:1.8.0_152]
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.write(JavaDefaultSerializers.java:242) ~[hazelcast-jet-0.6-20180109.155423-37.jar:0.6-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43) ~[hazelcast-jet-0.6-20180109.155423-37.jar:0.6-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:250) ~[hazelcast-jet-0.6-20180109.155423-37.jar:0.6-SNAPSHOT]
```
hazelcast/hazelcast#11851

### PR DESCRIPTION
**Pull request by eminn**
Replace internally used AbstractEntryProcessor inside updatingMap with a counterpart which implements IdentifiedDataSerializable to prevent Java Serialization.

Fixes #671

### CODE REVIEW

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java [hunk 1]
```diff
@@ -487,4 +483,64 @@ private boolean isRemote() {
...
+        @Override
+        public Object process(Entry<K, V> entry) {
+            V oldValue = entry.getValue();
+            T item = tmpMap.get(entry.getKey());
+            V newValue = updateFn.apply(oldValue, item);
+            entry.setValue(newValue);
+            return null;
+        }
+
+        @Override public EntryBackupProcessor<K, V> getBackupProcessor() {
```
Comment (cangencer) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java]: line breaks at `@Override` need fixing

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java [hunk 2]
```diff
@@ -487,4 +483,64 @@ private boolean isRemote() {
...
+            return this;
+        }
+
+        @Override public void writeData(ObjectDataOutput out) throws IOException {
+            out.writeInt(tmpMap.size());
+            for (Entry<K, T> entry : tmpMap.entrySet()) {
```
Comment (cangencer) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java]: there's already serializer for HashMap (see HashMapHook), so you don't need to re-implement it here.

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java [hunk 3]
```diff
@@ -487,4 +483,64 @@ private boolean isRemote() {
                          .limit(count).collect(toList());
         }
     }
+
+    public static class ApplyFnEntryProcessor<K, V, T> implements EntryProcessor<K, V>, EntryBackupProcessor,
+            IdentifiedDataSerializable {
+        private Map<K, T> tmpMap;
```
Comment (cangencer) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java]: tmpMap could be renamed to something else.. something like keysToUpdate ?

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java [hunk 4]
```diff
@@ -487,4 +483,64 @@ private boolean isRemote() {
                          .limit(count).collect(toList());
         }
     }
+
+    public static class ApplyFnEntryProcessor<K, V, T> implements EntryProcessor<K, V>, EntryBackupProcessor,
```
Comment (cangencer) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java]: EntryBackupProcessor implemention should be generic as well

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/SinksTest.java [hunk 5]
```diff
@@ -253,6 +258,30 @@ public void mapWithUpdating_when_functionReturnsNull_then_keyIsRemoved() {
...
+        // When
+        pipeline.drawFrom(Sources.<String, DataSerializableObject>map(srcName))
+                .drainTo(Sinks.mapWithUpdating(srcName,
+                        (DataSerializableObject value, Entry<String, DataSerializableObject> item) ->
+                                new DataSerializableObject(value.value + item.getValue().value)));
+        execute();
+
+        // Then
+        List<Entry<String, DataSerializableObject>> expected = input.stream()
+                                                                    .map(i -> entry(String.valueOf(i),
```
Comment (cangencer) [inline hazelcast-jet-core/src/test/java/com/hazelcast/jet/SinksTest.java]: can we fix the indentation here

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/SinksTest.java [hunk 6]
```diff
@@ -309,6 +338,31 @@ public void remoteMapWithUpdating_when_functionReturnsNull_then_keyIsRemoved() {
...
+        // When
+        pipeline.drawFrom(Sources.<String, DataSerializableObject>remoteMap(srcName, clientConfig))
+                .drainTo(Sinks.remoteMapWithUpdating(srcName, clientConfig,
+                        (DataSerializableObject value, Entry<String, DataSerializableObject> item) ->
+                                new DataSerializableObject(value.value + item.getValue().value)));
+        execute();
+
+        // Then
+        List<Entry<String, DataSerializableObject>> expected = input.stream()
+                                                                    .map(i -> entry(String.valueOf(i),
```
Comment (cangencer) [inline hazelcast-jet-core/src/test/java/com/hazelcast/jet/SinksTest.java]: same as above

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/SinksTest.java [hunk 7]
```diff
@@ -388,4 +442,40 @@ public Object process(Entry<K, Integer> entry) {
...
+        int value;
+
+        DataSerializableObject() {
+        }
+
+        DataSerializableObject(int value) {
+            this.value = value;
+        }
+
+        @Override public void writeData(ObjectDataOutput out) throws IOException {
```
Comment (cangencer) [inline hazelcast-jet-core/src/test/java/com/hazelcast/jet/SinksTest.java]: same problem with line breaks here, seems something wrong with your IDE setting?
