### PR TITLE
Use hostname equality if reverse lookup throws UnknownHostException exception

### LINKED ISSUE #810: Do no fail job if HDFS Source reverse DNS lookup fails
Currently when the Jet HDFS source tries to distribute HDFS splits to all the members it tries to make use of data locality by matching the IP address of the member to the hostname of the datanode where a split is present. The member IP address is converted to a hostname using a reverse DNS lookup. However if the lookup fails with `UnknownHostException` the job will fail to start. Even though this typically points to a configuration error, it might be better to print a warning instead and not fail the job. The caveat will be that Jet will not be able to make use of data locality if reverse DNS resolution isn't working.

Alternatively, we could only use forward lookups and match HDFS hosts against IP addresses instead.

### PR DESCRIPTION
**Pull request by gurbuzali**
fixes #810

### CODE REVIEW

File: hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/hadoop/impl/ReadHdfsP.java [hunk 1]
```diff
@@ -266,6 +267,18 @@ private static boolean isSplitLocalForMember(InputSplit split, Address memberAdd
                 return Arrays.stream(split.getLocations())
                         .flatMap(loc -> Arrays.stream(uncheckCall(() -> InetAddress.getAllByName(loc))))
                         .anyMatch(inetAddr::equals);
+            } catch (IOException e) {
+                if (e instanceof UnknownHostException) {
+                    return isSplitLocalForMember(split, memberAddr.getScopedHost());
```
Comment (viliam-durina) [inline hazelcast-jet-hadoop/src/main/java/com/hazelcast/jet/hadoop/impl/ReadHdfsP.java]: We should log this at warning level if it happens.
