### PR TITLE
Fix WriteKafkaPTest.test_resumeTransaction failure

### LINKED ISSUE #2398: com.hazelcast.jet.kafka.impl.WriteKafkaPTest.test_resumeTransaction
_master_ (commit c63abb54f06eac73f31706a2226f70812987e8af)

Failed on Zulu JDK 8: http://jenkins.hazelcast.com/job/jet-oss-master-zulu-jdk8/234/testReport/junit/com.hazelcast.jet.kafka.impl/WriteKafkaPTest/test_resumeTransaction/

Stacktrace:
```
org.junit.ComparisonFailure: 
expected:<[0
1
]> but was:<[]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.jet.kafka.impl.WriteKafkaPTest.test_resumeTransaction(WriteKafkaPTest.java:272)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Hiccups measured while running test 'test_resumeTransaction(com.hazelcast.jet.kafka.impl.WriteKafkaPTest):'
02:08:50, accumulated pauses: 1226 ms, max pause: 294 ms, pauses over 1000 ms: 0
02:08:55, accumulated pauses: 2956 ms, max pause: 1774 ms, pauses over 1000 ms: 1
02:09:00, accumulated pauses: 1335 ms, max pause: 83 ms, pauses over 1000 ms: 0
02:09:05, accumulated pauses: 1108 ms, max pause: 194 ms, pauses over 1000 ms: 0
```

### PR DESCRIPTION
**Pull request by viliam-durina**
We waited for 2 seconds for the kafka to deliver the results, probably
it wasn't long enough. Also it could happen that we receive 1 record and
don't poll for the next, even though it wasn't the case this time.

An attempt to fix #2398

### CODE REVIEW

File: extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/WriteKafkaPTest.java [hunk 1]
```diff
@@ -264,10 +264,14 @@ public void test_resumeTransaction() throws Exception {
         producer.commitTransaction();
 
         // verify items are visible
-        polledRecords = consumer.poll(Duration.ofSeconds(2));
         StringBuilder actualContents = new StringBuilder();
-        for (ConsumerRecord<String, String> record : polledRecords) {
-            actualContents.append(record.value()).append('\n');
+        for (int receivedCount = 0; receivedCount < 2; ) {
```
Comment (frant-hartm) [inline extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/WriteKafkaPTest.java:268]: This will loop indefinitely if the records aren't received, failing with a generic test timeout.

Wouldn't it be better to try the poll several times and eventually fail with an error message saying "didn't receive X records within 30 seconds" or similar?

Comment (viliam-durina) [reply extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/WriteKafkaPTest.java:268]: Yeah, it would be better, but I think it's enough for now. The test maybe never failed.
