### PR TITLE
Fix file name extraction on Windows

### LINKED ISSUE #2300: JobConfig.attachFile fails on windows
Reproduces in `DeploymentTest` tests, they fail with:
```
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/work/hazelcast/hazelcast-jet/hazelcast-jet-core/target/test-classes/deployment/resource.txt

	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.hazelcast.jet.impl.JobRepository.uploadJobResources(JobRepository.java:215)
	at com.hazelcast.jet.impl.AbstractJetInstance.uploadResourcesAndAssignId(AbstractJetInstance.java:183)
	at com.hazelcast.jet.impl.AbstractJetInstance.newJob(AbstractJetInstance.java:66)
	at com.hazelcast.jet.JetInstance.newJob(JetInstance.java:142)
	at com.hazelcast.jet.impl.deployment.AbstractDeploymentTest.testDeployment_whenAttachFile_thenFileAvailableOnMembers(AbstractDeploymentTest.java:173)
...
```

### PR DESCRIPTION
**Pull request by viliam-durina**
Fixes #2300

### CODE REVIEW

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java [hunk 1]
```diff
@@ -464,4 +465,22 @@ public static ProcessingGuarantee min(ProcessingGuarantee g1, ProcessingGuarante
...
+
+    /**
+     * Extracts the file name from the URL. File name is the part of {@code
+     * url.getPath()} after the last '/' character. Returns empty string if the
+     * path ends with a '/'.
+     * <p>
+     * Returns null if input is null or if {@code url.getPath()} returns null.
+     */
+    @Nullable
+    public static String fileNameFromUrl(@Nullable URL url) {
```
Comment (cangencer) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java:477]: minor but I think better to put this into `IOUtil`?

Comment (viliam-durina) [reply hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/util/Util.java]: done
