### PR TITLE
getJobStatus() should not throw when called right after submitting Job

### LINKED ISSUE #581: Exception on JobStatus query
When a job submitted from client or non-master member and if job status is queried, following exception is thrown

```
java.lang.IllegalArgumentException: Job 7c96-a61f-545d-7e52 not found
	at com.hazelcast.jet.impl.JobCoordinationService.getJobStatus(JobCoordinationService.java:309)
	at com.hazelcast.jet.impl.JetService.getJobStatus(JetService.java:166)
	at com.hazelcast.jet.impl.operation.GetJobStatusOperation.run(GetJobStatusOperation.java:45)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:194)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:569)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:554)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:513)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:207)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:60)
	at com.hazelcast.client.impl.protocol.task.AbstractInvocationMessageTask.processMessage(AbstractInvocationMessageTask.java:42)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123)
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:127)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.jet.impl.JetClientInstanceImpl.sendJobStatusRequest(JetClientInstanceImpl.java:120)
	at com.hazelcast.jet.impl.JetClientInstanceImpl.access$300(JetClientInstanceImpl.java:60)
	at com.hazelcast.jet.impl.JetClientInstanceImpl$SubmittedJobImpl.sendJobStatusRequest(JetClientInstanceImpl.java:161)
	at com.hazelcast.jet.impl.AbstractJobImpl.getJobStatus(AbstractJobImpl.java:89)
	at com.hazelcast.jet.tests.kafka.LongRunningKafkaSessionWindowTest.kafkaTest(LongRunningKafkaSessionWindowTest.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
	at com.hazelcast.jet.tests.kafka.LongRunningKafkaSessionWindowTest.main(LongRunningKafkaSessionWindowTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.hazelcast.jet.server.JetBootstrap.main(JetBootstrap.java:130)

FAILURES!!!
Tests run: 1,  Failures: 1
```

### PR DESCRIPTION
**Pull request by cangencer**
* As the job is submitted to the node asynchronously,  calling job.getJobStatus() can result in an exception if the job has not been recorded yet. Make the GetJobStatusOperation optionally retryable.
* Fixed an issue that if `ProcessorSupplier.complete()` throws `Throwable` it was not handled properly.
* Refactored  various job lifecycle test classes to move the test processors to a  common class.
* Fixes #581

### CODE REVIEW

**Comment by metanet** [comment]
good work

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java [hunk 1]
```diff
@@ -144,12 +144,13 @@ public boolean verify(Address coordinator, long jobId) {
     }
 
     // should not leak exceptions thrown by processor suppliers
+    // should not leak exceptions thrown by processor suppliers
```
Comment (viliam-durina) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java]: duplicated by mistake

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobStatusOperation.java [hunk 2]
```diff
@@ -51,6 +55,14 @@ public Object getResponse() {
     }
 
     @Override
+    public ExceptionAction onInvocationException(Throwable throwable) {
+        return throwable instanceof JobNotFoundException && retryOnNotFound ?
+                ExceptionAction.RETRY_INVOCATION
+                :
+                super.onInvocationException(throwable);
+    }
```
Comment (viliam-durina) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/GetJobStatusOperation.java]: Will look much better like this:
```
        return throwable instanceof JobNotFoundException && retryOnNotFound 
                ? ExceptionAction.RETRY_INVOCATION
                : super.onInvocationException(throwable);
```
