### PR TITLE
Set cluster connection timeout for MulticastDiscoveryTest

### LINKED ISSUE #2904: com.hazelcast.jet.MulticastDiscoveryTest.when_hazelcastClientCreated_then_doesNotConnectToJetCluster
_master_ (commit 5d4c7fe7863f784fff8d08e437ea8bc89dcb933a)

Failed on Sonar nightly build (Oracle JDK 11): http://jenkins.hazelcast.com/job/jet-oss-master-sonar-nightly/783/testReport/junit/com.hazelcast.jet/MulticastDiscoveryTest/when_hazelcastClientCreated_then_doesNotConnectToJetCluster/

Stacktrace:
```
java.lang.AssertionError: 

Expected: (an instance of java.lang.IllegalStateException and exception with message a string containing "Unable to connect")
     but: an instance of java.lang.IllegalStateException <org.junit.runners.model.TestTimedOutException: test timed out after 600000 milliseconds> is a org.junit.runners.model.TestTimedOutException
Stacktrace was: org.junit.runners.model.TestTimedOutException: test timed out after 600000 milliseconds
	at java.base@11/java.lang.Thread.sleep(Native Method)
	at app//com.hazelcast.client.impl.connection.tcp.WaitStrategy.sleep(WaitStrategy.java:75)
	at app//com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:501)
	at app//com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:406)
	at app//com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:367)
	at app//com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.start(TcpClientConnectionManager.java:316)
	at app//com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:369)
	at app//com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460)
	at app//com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416)
	at app//com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:119)
	at app//com.hazelcast.jet.MulticastDiscoveryTest.when_hazelcastClientCreated_then_doesNotConnectToJetCluster(MulticastDiscoveryTest.java:125)
	at java.base@11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base@11/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11/java.lang.Thread.run(Thread.java:834)

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at org.junit.rules.ExpectedException.handleException(ExpectedException.java:271)
	at org.junit.rules.ExpectedException.access$000(ExpectedException.java:111)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:260)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Standard output:
```
Started Running Test: when_hazelcastClientCreated_then_doesNotConnectToJetCluster
2021-02-23 03:04:21,395 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.i.m.i.MetricsConfigHelper]: [LOCAL] [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
2021-02-23 03:04:21,396 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.system]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Hazelcast Jet 4.5-SNAPSHOT (20210223 - 5d4c7fe) starting at [127.0.0.1]:5701
2021-02-23 03:04:21,397 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.system]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Based on Hazelcast IMDG version: 4.2.0 (20210222 - a5d5ef3)
2021-02-23 03:04:21,397 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.system]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Cluster name: ffa850db-8da9-46ec-9d2e-79771ca17985
2021-02-23 03:04:21,397 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.system]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] 
	o   o   o   o---o o---o o     o---o   o   o---o o-o-o        o o---o o-o-o
	|   |  / \     /  |     |     |      / \  |       |          | |       |
	o---o o---o   o   o-o   |     o     o---o o---o   |          | o-o     |
	|   | |   |  /    |     |     |     |   |     |   |      \   | |       |
	o   o o   o o---o o---o o---o o---o o   o o---o   o       o--o o---o   o
2021-02-23 03:04:21,397 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.system]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
2021-02-23 03:04:21,401 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.i.m.i.MetricsConfigHelper]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
2021-02-23 03:04:21,407 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.s.d.i.DiscoveryService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] No discovery strategy is applicable for auto-detection
2021-02-23 03:04:21,409 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.i.i.Node]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Using Multicast discovery
2021-02-23 03:04:21,409 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.CPSubsystem]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
2021-02-23 03:04:21,428 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.j.i.JetService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Setting number of cooperative threads and default parallelism to 72
2021-02-23 03:04:21,440 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.i.d.Diagnostics]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2021-02-23 03:04:21,441 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.LifecycleService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] [127.0.0.1]:5701 is STARTING
2021-02-23 03:04:23,475 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.i.c.ClusterService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - f1a05142-d53c-4947-ac05-e5b896181c46 this
]

2021-02-23 03:04:23,476 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.LifecycleService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] [127.0.0.1]:5701 is STARTED
2021-02-23 03:04:23,476 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:23,478 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.i.c.AbstractConfigLocator]: Loading 'hazelcast-client-default.xml' from the classpath.
2021-02-23 03:04:23,501 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.s.d.i.DiscoveryService]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] No discovery strategy is applicable for auto-detection
2021-02-23 03:04:23,502 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.s.ClientInvocationService]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Running with 2 response threads, dynamic=true
2021-02-23 03:04:23,504 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.LifecycleService]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] HazelcastClient 4.2-SNAPSHOT (20210222 - a5d5ef3) is STARTING
2021-02-23 03:04:23,504 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.LifecycleService]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] HazelcastClient 4.2-SNAPSHOT (20210222 - a5d5ef3) is STARTED
2021-02-23 03:04:23,525 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Trying to connect to cluster: dev
2021-02-23 03:04:23,525 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Trying to connect to [127.0.0.1]:5701
2021-02-23 03:04:23,532 [ WARN] [hz.lucid_tesla.priority-generic-operation.thread-0] [c.h.c.i.p.t.AuthenticationMessageTask]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Received auth from Connection[id=1, /127.0.0.1:5701->/127.0.0.1:57411, qualifier=null, endpoint=null, alive=true, connectionType=NONE, planeIndex=-1] with clientUuid 060c984d-8f60-400f-85a9-1c8e548b0ec9, authentication failed
2021-02-23 03:04:23,535 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.t.TcpClientConnection]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] ClientConnection{alive=false, connectionId=1, channel=NioChannel{/127.0.0.1:57411->/127.0.0.1:5701}, remoteAddress=null, lastReadTime=2021-02-23 03:04:23.534, lastWriteTime=2021-02-23 03:04:23.526, closedTime=2021-02-23 03:04:23.535, connected server version=null} closed. Reason: Failed to authenticate connection
com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.authenticateOnCluster(TcpClientConnectionManager.java:872) ~[hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.getOrConnectToAddress(TcpClientConnectionManager.java:594) ~[hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.lambda$doConnectToCandidateCluster$3(TcpClientConnectionManager.java:490) ~[hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connect(TcpClientConnectionManager.java:444) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:490) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:406) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:367) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.start(TcpClientConnectionManager.java:316) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:369) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:119) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.jet.MulticastDiscoveryTest.when_hazelcastClientCreated_then_doesNotConnectToJetCluster(MulticastDiscoveryTest.java:125) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.1.jar:4.13.1]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114) [hazelcast-4.2-SNAPSHOT-tests.jar:4.2-SNAPSHOT]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106) [hazelcast-4.2-SNAPSHOT-tests.jar:4.2-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-02-23 03:04:23,549 [ INFO] [hz.lucid_tesla.IO.thread-in-0] [c.h.i.s.t.TcpServerConnection]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Connection[id=1, /127.0.0.1:5701->/127.0.0.1:57411, qualifier=null, endpoint=null, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Connection closed by the other side
2021-02-23 03:04:23,550 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5701: com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
2021-02-23 03:04:23,550 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Trying to connect to [127.0.0.1]:5703
2021-02-23 03:04:23,551 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5703: com.hazelcast.core.HazelcastException: java.net.SocketException: Connection refused to address /127.0.0.1:5703
2021-02-23 03:04:23,551 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Trying to connect to [127.0.0.1]:5702
2021-02-23 03:04:23,551 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5702: com.hazelcast.core.HazelcastException: java.net.SocketException: Connection refused to address /127.0.0.1:5702
2021-02-23 03:04:23,552 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Unable to get live cluster connection, retry in 1000 ms, attempt: 1, cluster connect timeout: 9223372036854775807 ms, max backoff: 30000 ms
2021-02-23 03:04:23,576 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:23,677 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:23,777 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:23,877 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:23,978 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:24,078 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:24,179 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:24,279 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:24,379 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:24,480 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:24,552 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Trying to connect to [127.0.0.1]:5701
2021-02-23 03:04:24,554 [ WARN] [hz.lucid_tesla.priority-generic-operation.thread-0] [c.h.c.i.p.t.AuthenticationMessageTask]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Received auth from Connection[id=2, /127.0.0.1:5701->/127.0.0.1:46241, qualifier=null, endpoint=null, alive=true, connectionType=NONE, planeIndex=-1] with clientUuid 060c984d-8f60-400f-85a9-1c8e548b0ec9, authentication failed
2021-02-23 03:04:24,555 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.t.TcpClientConnection]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] ClientConnection{alive=false, connectionId=2, channel=NioChannel{/127.0.0.1:46241->/127.0.0.1:5701}, remoteAddress=null, lastReadTime=2021-02-23 03:04:24.554, lastWriteTime=2021-02-23 03:04:24.553, closedTime=2021-02-23 03:04:24.554, connected server version=null} closed. Reason: Failed to authenticate connection
com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.authenticateOnCluster(TcpClientConnectionManager.java:872) ~[hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.getOrConnectToAddress(TcpClientConnectionManager.java:594) ~[hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.lambda$doConnectToCandidateCluster$3(TcpClientConnectionManager.java:490) ~[hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connect(TcpClientConnectionManager.java:444) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:490) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:406) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:367) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.start(TcpClientConnectionManager.java:316) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:369) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:119) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.jet.MulticastDiscoveryTest.when_hazelcastClientCreated_then_doesNotConnectToJetCluster(MulticastDiscoveryTest.java:125) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.1.jar:4.13.1]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114) [hazelcast-4.2-SNAPSHOT-tests.jar:4.2-SNAPSHOT]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106) [hazelcast-4.2-SNAPSHOT-tests.jar:4.2-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-02-23 03:04:24,555 [ INFO] [hz.lucid_tesla.IO.thread-in-1] [c.h.i.s.t.TcpServerConnection]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Connection[id=2, /127.0.0.1:5701->/127.0.0.1:46241, qualifier=null, endpoint=null, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Connection closed by the other side
2021-02-23 03:04:24,556 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5701: com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
2021-02-23 03:04:24,557 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Trying to connect to [127.0.0.1]:5702
2021-02-23 03:04:24,557 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5702: com.hazelcast.core.HazelcastException: java.net.SocketException: Connection refused to address /127.0.0.1:5702
2021-02-23 03:04:24,557 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Trying to connect to [127.0.0.1]:5703
2021-02-23 03:04:24,557 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5703: com.hazelcast.core.HazelcastException: java.net.SocketException: Connection refused to address /127.0.0.1:5703
2021-02-23 03:04:24,557 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Unable to get live cluster connection, retry in 1050 ms, attempt: 2, cluster connect timeout: 9223372036854775807 ms, max backoff: 30000 ms
2021-02-23 03:04:24,580 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:24,680 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:24,781 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:24,881 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:24,981 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:25,082 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:25,182 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:25,283 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:25,383 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:25,483 [DEBUG] [hz.lucid_tesla.cached.thread-2] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:25,584 [DEBUG] [hz.lucid_tesla.cached.thread-2] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:25,608 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Trying to connect to [127.0.0.1]:5701
2021-02-23 03:04:25,610 [ WARN] [hz.lucid_tesla.priority-generic-operation.thread-0] [c.h.c.i.p.t.AuthenticationMessageTask]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Received auth from Connection[id=3, /127.0.0.1:5701->/127.0.0.1:60431, qualifier=null, endpoint=null, alive=true, connectionType=NONE, planeIndex=-1] with clientUuid 060c984d-8f60-400f-85a9-1c8e548b0ec9, authentication failed
2021-02-23 03:04:25,611 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.t.TcpClientConnection]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] ClientConnection{alive=false, connectionId=3, channel=NioChannel{/127.0.0.1:60431->/127.0.0.1:5701}, remoteAddress=null, lastReadTime=2021-02-23 03:04:25.610, lastWriteTime=2021-02-23 03:04:25.609, closedTime=2021-02-23 03:04:25.610, connected server version=null} closed. Reason: Failed to authenticate connection
com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.authenticateOnCluster(TcpClientConnectionManager.java:872) ~[hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.getOrConnectToAddress(TcpClientConnectionManager.java:594) ~[hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.lambda$doConnectToCandidateCluster$3(TcpClientConnectionManager.java:490) ~[hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connect(TcpClientConnectionManager.java:444) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:490) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:406) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:367) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.start(TcpClientConnectionManager.java:316) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:369) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:119) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.jet.MulticastDiscoveryTest.when_hazelcastClientCreated_then_doesNotConnectToJetCluster(MulticastDiscoveryTest.java:125) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.1.jar:4.13.1]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114) [hazelcast-4.2-SNAPSHOT-tests.jar:4.2-SNAPSHOT]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106) [hazelcast-4.2-SNAPSHOT-tests.jar:4.2-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-02-23 03:04:25,612 [ INFO] [hz.lucid_tesla.IO.thread-in-2] [c.h.i.s.t.TcpServerConnection]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Connection[id=3, /127.0.0.1:5701->/127.0.0.1:60431, qualifier=null, endpoint=null, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Connection closed by the other side
2021-02-23 03:04:25,615 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5701: com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
2021-02-23 03:04:25,615 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Trying to connect to [127.0.0.1]:5702
2021-02-23 03:04:25,616 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5702: com.hazelcast.core.HazelcastException: java.net.SocketException: Connection refused to address /127.0.0.1:5702
2021-02-23 03:04:25,616 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Trying to connect to [127.0.0.1]:5703
2021-02-23 03:04:25,616 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5703: com.hazelcast.core.HazelcastException: java.net.SocketException: Connection refused to address /127.0.0.1:5703
2021-02-23 03:04:25,616 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Unable to get live cluster connection, retry in 1102 ms, attempt: 3, cluster connect timeout: 9223372036854775807 ms, max backoff: 30000 ms
2021-02-23 03:04:25,684 [DEBUG] [hz.lucid_tesla.cached.thread-2] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:25,785 [DEBUG] [hz.lucid_tesla.cached.thread-2] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:25,885 [DEBUG] [hz.lucid_tesla.cached.thread-2] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:25,985 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:26,086 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:26,186 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:26,287 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:26,387 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:26,488 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:26,588 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:26,689 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:26,719 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Trying to connect to [127.0.0.1]:5701
2021-02-23 03:04:26,720 [ WARN] [hz.lucid_tesla.priority-generic-operation.thread-0] [c.h.c.i.p.t.AuthenticationMessageTask]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Received auth from Connection[id=4, /127.0.0.1:5701->/127.0.0.1:49155, qualifier=null, endpoint=null, alive=true, connectionType=NONE, planeIndex=-1] with clientUuid 060c984d-8f60-400f-85a9-1c8e548b0ec9, authentication failed
2021-02-23 03:04:26,721 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.t.TcpClientConnection]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] ClientConnection{alive=false, connectionId=4, channel=NioChannel{/127.0.0.1:49155->/127.0.0.1:5701}, remoteAddress=null, lastReadTime=2021-02-23 03:04:26.720, lastWriteTime=2021-02-23 03:04:26.720, closedTime=2021-02-23 03:04:26.721, connected server version=null} closed. Reason: Failed to authenticate connection
com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.authenticateOnCluster(TcpClientConnectionManager.java:872) ~[hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.getOrConnectToAddress(TcpClientConnectionManager.java:594) ~[hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.lambda$doConnectToCandidateCluster$3(TcpClientConnectionManager.java:490) ~[hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connect(TcpClientConnectionManager.java:444) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:490) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:406) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:367) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.start(TcpClientConnectionManager.java:316) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:369) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:119) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.jet.MulticastDiscoveryTest.when_hazelcastClientCreated_then_doesNotConnectToJetCluster(MulticastDiscoveryTest.java:125) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.1.jar:4.13.1]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114) [hazelcast-4.2-SNAPSHOT-tests.jar:4.2-SNAPSHOT]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106) [hazelcast-4.2-SNAPSHOT-tests.jar:4.2-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-02-23 03:04:26,722 [ INFO] [hz.lucid_tesla.IO.thread-in-3] [c.h.i.s.t.TcpServerConnection]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Connection[id=4, /127.0.0.1:5701->/127.0.0.1:49155, qualifier=null, endpoint=null, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Connection closed by the other side
2021-02-23 03:04:26,722 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5701: com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
2021-02-23 03:04:26,723 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Trying to connect to [127.0.0.1]:5703
2021-02-23 03:04:26,724 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5703: com.hazelcast.core.HazelcastException: java.net.SocketException: Connection refused to address /127.0.0.1:5703
2021-02-23 03:04:26,724 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Trying to connect to [127.0.0.1]:5702
2021-02-23 03:04:26,724 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5702: com.hazelcast.core.HazelcastException: java.net.SocketException: Connection refused to address /127.0.0.1:5702
2021-02-23 03:04:26,724 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Unable to get live cluster connection, retry in 1157 ms, attempt: 4, cluster connect timeout: 9223372036854775807 ms, max backoff: 30000 ms
2021-02-23 03:04:26,789 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:26,889 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:26,990 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:27,090 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:27,191 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:27,291 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:27,391 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:27,492 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:27,592 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:27,693 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:27,793 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:04:27,882 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Trying to connect to [127.0.0.1]:5701
2021-02-23 03:04:27,883 [ WARN] [hz.lucid_tesla.priority-generic-operation.thread-0] [c.h.c.i.p.t.AuthenticationMessageTask]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Received auth from Connection[id=5, /127.0.0.1:5701->/127.0.0.1:42709, qualifier=null, endpoint=null, alive=true, connectionType=NONE, planeIndex=-1] with clientUuid 060c984d-8f60-400f-85a9-1c8e548b0ec9, authentication failed
2021-02-23 03:04:27,884 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.t.TcpClientConnection]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] ClientConnection{alive=false, connectionId=5, channel=NioChannel{/127.0.0.1:42709->/127.0.0.1:5701}, remoteAddress=null, lastReadTime=2021-02-23 03:04:27.883, lastWriteTime=2021-02-23 03:04:27.883, closedTime=2021-02-23 03:04:27.883, connected server version=null} closed. Reason: Failed to authenticate connection
com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.authenticateOnCluster(TcpClientConnectionManager.java:872) ~[hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.getOrConnectToAddress(TcpClientConnectionManager.java:594) ~[hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.lambda$doConnectToCandidateCluster$3(TcpClientConnectionManager.java:490) ~[hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connect(TcpClientConnectionManager.java:444) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCandidateCluster(TcpClientConnectionManager.java:490) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.doConnectToCluster(TcpClientConnectionManager.java:406) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.connectToCluster(TcpClientConnectionManager.java:367) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnectionManager.start(TcpClientConnectionManager.java:316) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:369) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:119) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.jet.MulticastDiscoveryTest.when_hazelcastClientCreated_then_doesNotConnectToJetCluster(MulticastDiscoveryTest.java:125) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.1.jar:4.13.1]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114) [hazelcast-4.2-SNAPSHOT-tests.jar:4.2-SNAPSHOT]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106) [hazelcast-4.2-SNAPSHOT-tests.jar:4.2-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-02-23 03:04:27,884 [ INFO] [hz.lucid_tesla.IO.thread-in-0] [c.h.i.s.t.TcpServerConnection]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Connection[id=5, /127.0.0.1:5701->/127.0.0.1:42709, qualifier=null, endpoint=null, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Connection closed by the other side
2021-02-23 03:04:27,885 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5701: com.hazelcast.client.AuthenticationException: Authentication failed. The configured cluster name on the client (see ClientConfig.setClusterName()) does not match the one configured in the cluster or the credentials set in the Client security config could not be authenticated
2021-02-23 03:04:27,885 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Trying to connect to [127.0.0.1]:5703
2021-02-23 03:04:27,885 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Exception during initial connection to [127.0.0.1]:5703: com.hazelcast.core.HazelcastException: java.net.SocketException: Con
...[truncated 1877072 chars]...
h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:08,310 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:08,410 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:08,510 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:08,610 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:08,710 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:08,810 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:08,910 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:09,010 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:09,111 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:09,211 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:09,311 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:09,411 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:09,494 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:09,511 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:09,611 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:09,711 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:09,811 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:09,912 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:10,012 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:10,112 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:10,212 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:10,312 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:10,412 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:10,512 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:10,612 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:10,713 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:10,813 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:10,913 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:11,013 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:11,113 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:11,213 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:11,313 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:11,413 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:11,494 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:11,513 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:11,613 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:11,714 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:11,814 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:11,914 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:12,014 [DEBUG] [hz.lucid_tesla.cached.thread-14] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:12,114 [DEBUG] [hz.lucid_tesla.cached.thread-14] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:12,214 [DEBUG] [hz.lucid_tesla.cached.thread-14] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:12,314 [DEBUG] [hz.lucid_tesla.cached.thread-14] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:12,414 [DEBUG] [hz.lucid_tesla.cached.thread-14] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:12,514 [DEBUG] [hz.lucid_tesla.cached.thread-14] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:12,615 [DEBUG] [hz.lucid_tesla.cached.thread-14] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:12,715 [DEBUG] [hz.lucid_tesla.cached.thread-14] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:12,815 [DEBUG] [hz.lucid_tesla.cached.thread-14] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:12,915 [DEBUG] [hz.lucid_tesla.cached.thread-14] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:13,015 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:13,115 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:13,215 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:13,315 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:13,416 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:13,494 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:13,516 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:13,616 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:13,716 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:13,816 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:13,916 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:14,016 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:14,116 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:14,216 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:14,316 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:14,416 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:14,517 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:14,617 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:14,717 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:14,817 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:14,917 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:15,017 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:15,117 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:15,217 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:15,317 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:15,417 [DEBUG] [hz.lucid_tesla.cached.thread-4] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:15,495 [DEBUG] [hz.lucid_tesla.cached.thread-7] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:15,517 [DEBUG] [hz.lucid_tesla.cached.thread-7] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:15,618 [DEBUG] [hz.lucid_tesla.cached.thread-7] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:15,718 [DEBUG] [hz.lucid_tesla.cached.thread-7] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:15,818 [DEBUG] [hz.lucid_tesla.cached.thread-7] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:15,918 [DEBUG] [hz.lucid_tesla.cached.thread-7] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:16,018 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:16,118 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:16,218 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:16,318 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:16,418 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:16,518 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:16,618 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:16,719 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:16,819 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:16,919 [DEBUG] [hz.lucid_tesla.cached.thread-6] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:17,019 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:17,119 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:17,219 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:17,319 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:17,419 [DEBUG] [hz.lucid_tesla.cached.thread-12] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:17,495 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:17,519 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:17,619 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:17,719 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:17,820 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:17,920 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:18,020 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:18,120 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:18,220 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:18,320 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:18,420 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:18,520 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:18,620 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:18,720 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:18,821 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:18,921 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:19,021 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:19,121 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:19,221 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:19,321 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:19,421 [DEBUG] [hz.lucid_tesla.cached.thread-14] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:19,495 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:19,521 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:19,621 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:19,721 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:19,822 [DEBUG] [hz.lucid_tesla.cached.thread-3] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:19,922 [DEBUG] [hz.lucid_tesla.cached.thread-7] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:20,022 [DEBUG] [hz.lucid_tesla.cached.thread-7] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:20,122 [DEBUG] [hz.lucid_tesla.cached.thread-7] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:20,222 [DEBUG] [hz.lucid_tesla.cached.thread-7] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:20,322 [DEBUG] [hz.lucid_tesla.cached.thread-7] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:20,422 [DEBUG] [hz.lucid_tesla.cached.thread-12] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:20,522 [DEBUG] [hz.lucid_tesla.cached.thread-7] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:20,622 [DEBUG] [hz.lucid_tesla.cached.thread-7] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:20,722 [DEBUG] [hz.lucid_tesla.cached.thread-7] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:20,823 [DEBUG] [hz.lucid_tesla.cached.thread-7] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:20,923 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:21,023 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:21,123 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:21,223 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:21,323 [DEBUG] [hz.lucid_tesla.cached.thread-5] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-23 03:14:21,398 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.i.c.ClientConnectionManager]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Unable to connect to any address from the cluster with name: dev. The following addresses were tried: [[127.0.0.1]:5703, [127.0.0.1]:5702, [127.0.0.1]:5701]
2021-02-23 03:14:21,398 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.LifecycleService]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] HazelcastClient 4.2-SNAPSHOT (20210222 - a5d5ef3) is SHUTTING_DOWN
2021-02-23 03:14:21,400 [ INFO] [Time-limited test] [c.h.c.LifecycleService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
2021-02-23 03:14:21,400 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.s.i.e.TaskScheduler]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] internal executor await termination is interrupted
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1454) ~[?:?]
	at com.hazelcast.client.impl.spi.impl.ClientExecutionServiceImpl.awaitExecutorTermination(ClientExecutionServiceImpl.java:92) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.spi.impl.ClientExecutionServiceImpl.shutdown(ClientExecutionServiceImpl.java:87) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.doShutdown(HazelcastClientInstanceImpl.java:777) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.clientside.LifecycleServiceImpl.doShutdown(LifecycleServiceImpl.java:172) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.clientside.LifecycleServiceImpl.terminate(LifecycleServiceImpl.java:155) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:412) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:119) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.jet.MulticastDiscoveryTest.when_hazelcastClientCreated_then_doesNotConnectToJetCluster(MulticastDiscoveryTest.java:125) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.1.jar:4.13.1]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114) [hazelcast-4.2-SNAPSHOT-tests.jar:4.2-SNAPSHOT]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106) [hazelcast-4.2-SNAPSHOT-tests.jar:4.2-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-02-23 03:14:21,401 [ INFO] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.LifecycleService]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] HazelcastClient 4.2-SNAPSHOT (20210222 - a5d5ef3) is SHUTDOWN
2021-02-23 03:14:21,401 [ WARN] [when_hazelcastClientCreated_then_doesNotConnectToJetCluster] [c.h.c.LifecycleService]: hz.client_2 [dev] [4.5-SNAPSHOT] [4.2-SNAPSHOT] LifecycleService executor awaitTermination is interrupted. Terminating forcefully.
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1454) ~[?:?]
	at java.util.concurrent.Executors$DelegatedExecutorService.awaitTermination(Executors.java:709) ~[?:?]
	at com.hazelcast.client.impl.clientside.LifecycleServiceImpl.shutdownExecutor(LifecycleServiceImpl.java:182) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.clientside.LifecycleServiceImpl.doShutdown(LifecycleServiceImpl.java:175) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.clientside.LifecycleServiceImpl.terminate(LifecycleServiceImpl.java:155) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:412) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.constructHazelcastClient(HazelcastClient.java:460) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.newHazelcastClientInternal(HazelcastClient.java:416) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:119) [hazelcast-4.2-SNAPSHOT.jar:4.2-SNAPSHOT]
	at com.hazelcast.jet.MulticastDiscoveryTest.when_hazelcastClientCreated_then_doesNotConnectToJetCluster(MulticastDiscoveryTest.java:125) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.13.1.jar:4.13.1]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [junit-4.13.1.jar:4.13.1]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.13.1.jar:4.13.1]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114) [hazelcast-4.2-SNAPSHOT-tests.jar:4.2-SNAPSHOT]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106) [hazelcast-4.2-SNAPSHOT-tests.jar:4.2-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-02-23 03:14:21,402 [ INFO] [Time-limited test] [c.h.i.i.Node]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Shutting down multicast service...
2021-02-23 03:14:21,402 [ INFO] [Time-limited test] [c.h.i.i.Node]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Shutting down connection manager...
2021-02-23 03:14:21,404 [ INFO] [Time-limited test] [c.h.i.i.Node]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Shutting down node engine...
2021-02-23 03:14:21,421 [ INFO] [Time-limited test] [c.h.i.i.NodeExtension]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Destroying node NodeExtension.
2021-02-23 03:14:21,422 [ INFO] [Time-limited test] [c.h.i.i.Node]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] Hazelcast Shutdown is completed in 21 ms.
2021-02-23 03:14:21,423 [ INFO] [Time-limited test] [c.h.c.LifecycleService]: [127.0.0.1]:5701 [ffa850db-8da9-46ec-9d2e-79771ca17985] [4.5-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after when_hazelcastClientCreated_then_doesNotConnectToJetCluster(com.hazelcast.jet.MulticastDiscoveryTest): BuildInfo{version='4.2-SNAPSHOT', build='20210222', buildNumber=20210222, revision=a5d5ef3, enterprise=false, serializationVersion=1, jet=JetBuildInfo{version='4.5-SNAPSHOT', build='20210223', revision='5d4c7fe'}}
Hiccups measured while running test 'when_hazelcastClientCreated_then_doesNotConnectToJetCluster(com.hazelcast.jet.MulticastDiscoveryTest):'
03:04:20, accumulated pauses: 36 ms, max pause: 9 ms, pauses over 1000 ms: 0
03:04:25, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:04:30, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:04:35, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:04:40, accumulated pauses: 38 ms, max pause: 4 ms, pauses over 1000 ms: 0
03:04:45, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:04:50, accumulated pauses: 31 ms, max pause: 1 ms, pauses over 1000 ms: 0
03:04:55, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:05:00, accumulated pauses: 30 ms, max pause: 1 ms, pauses over 1000 ms: 0
03:05:05, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:05:10, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:05:15, accumulated pauses: 28 ms, max pause: 2 ms, pauses over 1000 ms: 0
03:05:20, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:05:25, accumulated pauses: 26 ms, max pause: 1 ms, pauses over 1000 ms: 0
03:05:30, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:05:35, accumulated pauses: 32 ms, max pause: 2 ms, pauses over 1000 ms: 0
03:05:40, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:05:45, accumulated pauses: 28 ms, max pause: 1 ms, pauses over 1000 ms: 0
03:05:50, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:05:55, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:06:00, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:06:05, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:06:10, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:06:15, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:06:20, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:06:25, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:06:30, accumulated pauses: 26 ms, max pause: 1 ms, pauses over 1000 ms: 0
03:06:35, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:06:40, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:06:45, accumulated pauses: 32 ms, max pause: 1 ms, pauses over 1000 ms: 0
03:06:50, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:06:55, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:07:00, accumulated pauses: 32 ms, max pause: 1 ms, pauses over 1000 ms: 0
03:07:05, accumulated pauses: 33 ms, max pause: 2 ms, pauses over 1000 ms: 0
03:07:10, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:07:15, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:07:20, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:07:25, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:07:30, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:07:35, accumulated pauses: 27 ms, max pause: 1 ms, pauses over 1000 ms: 0
03:07:40, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:07:45, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:07:50, accumulated pauses: 30 ms, max pause: 1 ms, pauses over 1000 ms: 0
03:07:55, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:08:00, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:08:05, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:08:10, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:08:15, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:08:20, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:08:25, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:08:30, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:08:35, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:08:40, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:08:45, accumulated pauses: 29 ms, max pause: 1 ms, pauses over 1000 ms: 0
03:08:50, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:08:55, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:09:00, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:09:05, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:09:10, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:09:15, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:09:20, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:09:25, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:09:30, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:09:35, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:09:40, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:09:45, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:09:50, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:09:55, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:10:00, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:10:05, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:10:10, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:10:15, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:10:20, accumulated pauses: 23 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:10:25, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:10:30, accumulated pauses: 29 ms, max pause: 1 ms, pauses over 1000 ms: 0
03:10:35, accumulated pauses: 30 ms, max pause: 2 ms, pauses over 1000 ms: 0
03:10:40, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:10:45, accumulated pauses: 41 ms, max pause: 10 ms, pauses over 1000 ms: 0
03:10:50, accumulated pauses: 29 ms, max pause: 2 ms, pauses over 1000 ms: 0
03:10:55, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:11:00, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:11:05, accumulated pauses: 22 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:11:10, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:11:15, accumulated pauses: 23 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:11:20, accumulated pauses: 28 ms, max pause: 1 ms, pauses over 1000 ms: 0
03:11:25, accumulated pauses: 23 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:11:30, accumulated pauses: 22 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:11:35, accumulated pauses: 22 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:11:40, accumulated pauses: 23 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:11:45, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:11:50, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:11:55, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:12:00, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:12:05, accumulated pauses: 32 ms, max pause: 3 ms, pauses over 1000 ms: 0
03:12:10, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:12:15, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:12:20, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:12:25, accumulated pauses: 22 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:12:30, accumulated pauses: 22 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:12:35, accumulated pauses: 23 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:12:40, accumulated pauses: 23 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:12:45, accumulated pauses: 26 ms, max pause: 1 ms, pauses over 1000 ms: 0
03:12:50, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:12:55, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:13:00, accumulated pauses: 23 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:13:05, accumulated pauses: 23 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:13:10, accumulated pauses: 23 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:13:15, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:13:20, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:13:25, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:13:30, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:13:35, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:13:40, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:13:45, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:13:50, accumulated pauses: 32 ms, max pause: 2 ms, pauses over 1000 ms: 0
03:13:55, accumulated pauses: 22 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:14:00, accumulated pauses: 22 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:14:05, accumulated pauses: 23 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:14:10, accumulated pauses: 23 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:14:15, accumulated pauses: 23 ms, max pause: 0 ms, pauses over 1000 ms: 0
03:14:20, accumulated pauses: 6 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

### PR DESCRIPTION
**Pull request by gierlachg**
Recently, client started retrying indefinitely.
To fix the test, former cluster connection timeout has been set for the client.

Fixes #2904

### CODE REVIEW

**Comment by olukas** [comment]
run-nightly-tests

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/MulticastDiscoveryTest.java [hunk 1]
```diff
@@ -122,7 +130,13 @@ public void when_hazelcastClientCreated_then_doesNotConnectToJetCluster() {
 
         expectedException.expect(IllegalStateException.class);
         expectedException.expectMessage(UNABLE_TO_CONNECT_MESSAGE);
-        HazelcastClient.newHazelcastClient();
+
+        ClientConfig clientConfig = ClientConfig.load();
```
Comment (gurbuzali) [inline hazelcast-jet-core/src/test/java/com/hazelcast/jet/MulticastDiscoveryTest.java:134]: looks like we duplicate retry logic, move it to a method perhaps

Comment (gierlachg) [reply hazelcast-jet-core/src/test/java/com/hazelcast/jet/MulticastDiscoveryTest.java:134]: Not sure, what you mean exactly. Those are 2 different configs & clients. I would say resemblance is accidental.

**Comment by olukas** [comment]
I tried to run in on jenkins and one of tests still fails - http://jenkins.hazelcast.com/view/Jet%20-%20Misc/job/jet-custom-oss-nightly/lastCompletedBuild/testReport/com.hazelcast.jet/MulticastDiscoveryTest/when_jetClientCreated_then_doesNotConnectToHazelcastCluster/

I start the nightly tests directly for this PR through the comment - I expect the same issue will occur.

@gierlachg can you please take a look on it?

**Comment by olukas** [comment]
Ah, there was an update, ignore my previous comment.

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/MulticastDiscoveryTest.java (hunk 1 above)
Comment (gurbuzali) [reply hazelcast-jet-core/src/test/java/com/hazelcast/jet/MulticastDiscoveryTest.java:134]: I meant this part
```
private void configureTimeout(ClientConfig clientConfig) {
        clientConfig.getConnectionStrategyConfig()
                .getConnectionRetryConfig()
                .setClusterConnectTimeoutMillis(CLUSTER_CONNECTION_TIMEOUT);
}
```

**Review by gurbuzali — APPROVED** [review]

**Review by olukas — APPROVED** [review]
