### PR TITLE
Fix Kafka writer issues

### LINKED ISSUE #605: WriteKafkaP might not meet at least once guarantee
`KafkaProducer.send` is asynchronous. The Kafka sink might theoretically lose records when snapshot is made, job fails just after it and the async call is not complete yet.

### PR DESCRIPTION
**Pull request by viliam-durina**
KafkaProducer.send() call is async. This scenario was possible:
- send a record
- do a successful snapshot
- member fails before the async record is sent
- after restart, the record is lost and the at-least-once guarantee broken.

This was resolved that the processor ensures that all async calls are
done at the time of snapshot.

Another fixes:
- calling `producer.flush()` after each batch of items
- checking for errors from async calls

Fixes #605

### CODE REVIEW

File: hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/impl/connector/kafka/WriteKafkaP.java [hunk 1]
```diff
@@ -52,28 +73,56 @@ public boolean isCooperative() {
...
+        private static final long serialVersionUID = 1L;
+        private static final String MAX_BLOCK_MS = Long.toString(1L << 32);
 
         private final Properties properties;
         private final Function<? super T, ProducerRecord<K, V>> toRecordFn;
 
         private transient KafkaProducer<K, V> producer;
 
         public Supplier(Properties properties, Function<? super T, ProducerRecord<K, V>> toRecordFn) {
+            // use a large enough value: we don't handle the TimeoutException and we don't want to fail due to it.
```
Comment (gurbuzali) [inline hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/impl/connector/kafka/WriteKafkaP.java]: I think it would be good to add this information(that we override `max.block.ms`) to the JavaDoc

**Comment by cangencer** [comment]
Would there be any way to verify exactly-once behaviour with a test?

File: hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/KafkaSinks.java [hunk 2]
```diff
@@ -39,14 +39,17 @@ private KafkaSinks() {
...
+     * make sure that all async operations are done. If the job is restarted,
+     * duplicate events can occur. If you need exactly-once behavior, you must
+     * ensure idempotence on the application level.
      * <p>
-     * IO failures are generally handled by Kafka producer and generally do not
-     * cause the processor to fail. Refer to Kafka documentation for details.
+     * IO failures are generally handled by Kafka producer and do not cause the
+     * processor to fail. Refer to Kafka documentation for details.
+     * <p>
+     * The
```
Comment (cangencer) [inline hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/KafkaSinks.java]: seems leftover "The"

File: hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/impl/connector/kafka/WriteKafkaP.java [hunk 3]
```diff
@@ -36,10 +40,20 @@
...
-public final class WriteKafkaP<T, K, V> extends AbstractProcessor {
+public final class WriteKafkaP<T, K, V> implements Processor {
 
     private final KafkaProducer<K, V> producer;
     private final Function<T, ProducerRecord<K, V>> toRecordFn;
+    private final AtomicInteger numPendingAsyncCalls = new AtomicInteger();
+    private final AtomicReference<Throwable> lastError = new AtomicReference<>();
+
+    private final Callback callback = (metadata, exception) -> {
+        // Note: this method is called on different thread.
```
Comment (cangencer) [inline hazelcast-jet-kafka/src/main/java/com/hazelcast/jet/impl/connector/kafka/WriteKafkaP.java]: should say it *may* be called on a different thread instead.

**Comment by viliam-durina** [comment]
verify
