### PR TITLE
Fix outbox blocking in snapshot phase 2

### LINKED ISSUE #1881: AsyncTransformUsingServiceP_IntegrationTest.stressTest_withRestart[ordered=false]
_master_ (commit bfc756de4e7b6114df4c69265099e9ae89ffbd15)

Failed on: http://jenkins.hazelcast.com/job/jet-oss-pr-builder/1936/testReport/junit/com.hazelcast.jet.impl.processor/AsyncTransformUsingServiceP_IntegrationTest/stressTest_withRestart_ordered_false_/

Standard output:
```
13:46:57,167 DEBUG || - [MasterSnapshotContext] hz.goofy_margulis.cached.thread-10 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Starting snapshot 0 for job '03c8-e8cb-1e9d-0001', execution 03c8-e8cb-1e9e-0001, flags: terminal=no,export=no, writing to: null
13:46:57,168 DEBUG || - [AsyncSnapshotWriterImpl] hz.goofy_margulis.jet.cooperative.thread-68 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Stats for sink: keys=0, chunks=0, bytes=0
13:46:57,168 DEBUG || - [AsyncSnapshotWriterImpl] hz.goofy_margulis.jet.cooperative.thread-65 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Stats for map: keys=6, chunks=3, bytes=487
13:46:57,169 DEBUG || - [AsyncSnapshotWriterImpl] hz.goofy_margulis.jet.cooperative.thread-62 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Stats for source: keys=271, chunks=168, bytes=12,612
13:46:57,169 DEBUG || - [SnapshotPhase1Operation] hz.goofy_margulis.jet.cooperative.thread-62 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Snapshot 0 phase 1 for job '03c8-e8cb-1e9d-0001', execution 03c8-e8cb-1e9e-0001 finished successfully on member
13:46:57,169 DEBUG || - [MasterSnapshotContext] hz.goofy_margulis.cached.thread-10 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Snapshot 0 phase 1 for job '03c8-e8cb-1e9d-0001', execution 03c8-e8cb-1e9e-0001 completed with status SUCCESS in 3ms, 13,099 bytes, 277 keys in 171 chunks, stored in '__jet.snapshot.03c8-e8cb-1e9d-0001.0', proceeding to phase 2
13:46:57,170 DEBUG || - [JobRepository] hz.goofy_margulis.cached.thread-10 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Cleared snapshot data map __jet.snapshot.03c8-e8cb-1e9d-0001.1
13:46:57,170 DEBUG || - [ExecutionContext] hz.goofy_margulis.cached.thread-10 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Starting snapshot 0 phase 2 for job '03c8-e8cb-1e9d-0001', execution 03c8-e8cb-1e9e-0001 on member
13:46:57,460 DEBUG || - [Job] stressTest_withRestart - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Sending RESTART_GRACEFUL request for job 03c8-e8cb-1e9d-0001 (name ??)
13:46:57,460 DEBUG || - [MasterSnapshotContext] hz.goofy_margulis.cached.thread-10 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Not beginning snapshot since one is already in progress job '03c8-e8cb-1e9d-0001', execution 03c8-e8cb-1e9e-0001
13:47:00,723 DEBUG || - [JobRepository] hz.goofy_margulis.cached.thread-10 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Job cleanup took 1ms
13:47:05,726 DEBUG || - [JobRepository] hz.goofy_margulis.cached.thread-2 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Job cleanup took 0ms
13:47:10,730 DEBUG || - [JobRepository] hz.goofy_margulis.cached.thread-21 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Job cleanup took 1ms
13:47:15,734 DEBUG || - [JobRepository] hz.goofy_margulis.cached.thread-10 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Job cleanup took 1ms
13:47:20,737 DEBUG || - [JobRepository] hz.goofy_margulis.cached.thread-21 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Job cleanup took 1ms
```

The snapshot phase 2 was initiated on memger (`Starting snapshot 0 phase 2 for job '03c8-e8cb-1e9d-0001', execution 03c8-e8cb-1e9e-0001 on member`), but didn't finish. 300ms later job was requested to gracefully restart, but that was postponed due to the snapshot in progress, which is OK. But the snapshot in progress never completed, leaving the job stuck, even cancellation failed. Since the cluster is shared, we terminate it in that case and all subsequent tests in that class failed due to that.

### PR DESCRIPTION
**Pull request by viliam-durina**
This happened:

- in `ProcessorTasklet.processInbox` we discovered that a new phase-2 begun

- there was an unfinished item in the outbox, so we blocked the outbox and
didn't begin the phase-2 in order to ensure that the unfinished item is finished

- however before that, the processor had returned from `process()` with an
empty inbox and an unfinished item. Therefore the process went to `fillInbox`
and found a WM there. So the state proceeded to PROCESS_WATERMARK, but the
outbox was still blocked.

- `tryProcessWatermark` tried to emit the `currentTraverser` first, but
couldn't because the outbox was blocked. And there it remained stuck, trying
that forever.

Returning `true` from `tryProcess()` or returning an empty inbox and having an
unfinished item in the outbox is allowed. So we changed the contract of
`snapshotCommitFinish` that it must not add items to outbox and if there's a
phase-2, we just execute that method and return to where we left.

Fixes #1881

Checklist
- [x] Tags Set
- [x] Milestone Set
- [x] Any breaking changes are documented
- [x] New public APIs have `@Nonnull/@Nullable` annotations
- [x] New public APIs have `@since` tags in Javadoc
- [x] For code samples, code sample main readme is updated

### CODE REVIEW

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorState.java [hunk 1]
```diff
@@ -73,23 +73,32 @@
...
-    WAITING_FOR_SNAPSHOT_COMPLETED,
+    SNAPSHOT_COMMIT_FINISH__COMPLETE,
+
+    /**
+     * Making calls to {@link Processor#snapshotCommitFinish(boolean)} until it
+     * returns {@code true} and then proceed to {@link #EMIT_DONE_ITEM}. Used
+     * when phase-2 was initiated after {@code Processor.complete()} returned
+     * true.
+     */
+    SNAPSHOT_COMMIT_FINISH__FINAL,
```
Comment (cangencer) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorState.java]: is the double underscore intentional here? looks a little strange

Comment (viliam-durina) [reply hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ProcessorState.java]: yes, there are three constants starting with `SNAPSHOT_COMMIT_FINISH`, after the two underscores is the discriminating part, all three have `__`.

Checkstyle didn't object :)
