### PR TITLE
Fix race in MetricsContext

### LINKED ISSUE #2572: com.hazelcast.jet.core.metrics.MetricsTest issues
_master_ (commit 418a40701628c4fafaa063342de6b9c1adb1be13)

Failed on Oracle JDK 8: http://jenkins.hazelcast.com/job/jet-oss-master-oracle-jdk8/281/testReport/com.hazelcast.jet.core.metrics/

Following tests failed:
- `com.hazelcast.jet.core.metrics.MetricsTest.availableDuringJobExecution`
- `com.hazelcast.jet.core.metrics.MetricsTest.metricsAreJobIndependent`
- `com.hazelcast.jet.core.metrics.MetricsTest.test_sourceSinkTag`

Stacktrace for `com.hazelcast.jet.core.metrics.MetricsTest.availableDuringJobExecution` (and the same for `com.hazelcast.jet.core.metrics.MetricsTest.metricsAreJobIndependent` just from line `com.hazelcast.jet.core.metrics.MetricsTest.lambda$metricsAreJobIndependent$8(MetricsTest.java:392)`):
```
java.lang.AssertionError: Expected measurements for metric 'total', but there were none
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at com.hazelcast.jet.core.metrics.JobMetricsChecker.assertAggregatedMetricValue(JobMetricsChecker.java:75)
	at com.hazelcast.jet.core.metrics.JobMetricsChecker.assertSummedMetricValue(JobMetricsChecker.java:53)
	at com.hazelcast.jet.core.metrics.MetricsTest.lambda$availableDuringJobExecution$4(MetricsTest.java:256)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1458)
	at com.hazelcast.jet.core.metrics.MetricsTest.availableDuringJobExecution(MetricsTest.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Stacktrace for `com.hazelcast.jet.core.metrics.MetricsTest.test_sourceSinkTag`:
```
java.lang.AssertionError: Values should be different. Actual: 0
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failEquals(Assert.java:185)
	at org.junit.Assert.assertNotEquals(Assert.java:199)
	at org.junit.Assert.assertNotEquals(Assert.java:211)
	at com.hazelcast.jet.core.metrics.MetricsTest.lambda$test_sourceSinkTag$11(MetricsTest.java:443)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1458)
	at com.hazelcast.jet.core.metrics.MetricsTest.test_sourceSinkTag(MetricsTest.java:443)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output for `com.hazelcast.jet.core.metrics.MetricsTest.availableDuringJobExecution`:
```
Hiccups measured while running test 'availableDuringJobExecution(com.hazelcast.jet.core.metrics.MetricsTest):'
13:32:35, accumulated pauses: 311 ms, max pause: 281 ms, pauses over 1000 ms: 0
13:32:40, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:32:45, accumulated pauses: 65 ms, max pause: 3 ms, pauses over 1000 ms: 0
13:32:50, accumulated pauses: 57 ms, max pause: 4 ms, pauses over 1000 ms: 0
13:32:55, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:33:00, accumulated pauses: 31 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:33:05, accumulated pauses: 161 ms, max pause: 5 ms, pauses over 1000 ms: 0
13:33:10, accumulated pauses: 120 ms, max pause: 3 ms, pauses over 1000 ms: 0
13:33:15, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:33:20, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:33:25, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:33:30, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:33:35, accumulated pauses: 34 ms, max pause: 4 ms, pauses over 1000 ms: 0
13:33:40, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:33:45, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:33:50, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:33:55, accumulated pauses: 41 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:34:00, accumulated pauses: 42 ms, max pause: 5 ms, pauses over 1000 ms: 0
13:34:05, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:34:10, accumulated pauses: 30 ms, max pause: 2 ms, pauses over 1000 ms: 0
13:34:15, accumulated pauses: 32 ms, max pause: 2 ms, pauses over 1000 ms: 0
13:34:20, accumulated pauses: 55 ms, max pause: 21 ms, pauses over 1000 ms: 0
13:34:25, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:34:30, accumulated pauses: 35 ms, max pause: 2 ms, pauses over 1000 ms: 0
13:34:35, accumulated pauses: 312 ms, max pause: 293 ms, pauses over 1000 ms: 0
```

Standard output for `com.hazelcast.jet.core.metrics.MetricsTest.metricsAreJobIndependent`:
```
Hiccups measured while running test 'metricsAreJobIndependent(com.hazelcast.jet.core.metrics.MetricsTest):'
13:34:35, accumulated pauses: 323 ms, max pause: 293 ms, pauses over 1000 ms: 0
13:34:40, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:34:45, accumulated pauses: 45 ms, max pause: 3 ms, pauses over 1000 ms: 0
13:34:50, accumulated pauses: 32 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:34:55, accumulated pauses: 35 ms, max pause: 4 ms, pauses over 1000 ms: 0
13:35:00, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:35:05, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:35:10, accumulated pauses: 37 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:35:15, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:35:20, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:35:25, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:35:30, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:35:35, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:35:40, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:35:45, accumulated pauses: 29 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:35:50, accumulated pauses: 33 ms, max pause: 2 ms, pauses over 1000 ms: 0
13:35:55, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:36:00, accumulated pauses: 33 ms, max pause: 4 ms, pauses over 1000 ms: 0
13:36:05, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:36:10, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:36:15, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:36:20, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:36:25, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:36:30, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:36:35, accumulated pauses: 434 ms, max pause: 406 ms, pauses over 1000 ms: 0
```

Standard output for `com.hazelcast.jet.core.metrics.MetricsTest.test_sourceSinkTag`:
```
Hiccups measured while running test 'test_sourceSinkTag(com.hazelcast.jet.core.metrics.MetricsTest):'
13:30:35, accumulated pauses: 39 ms, max pause: 14 ms, pauses over 1000 ms: 0
13:30:40, accumulated pauses: 27 ms, max pause: 2 ms, pauses over 1000 ms: 0
13:30:45, accumulated pauses: 51 ms, max pause: 7 ms, pauses over 1000 ms: 0
13:30:50, accumulated pauses: 27 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:30:55, accumulated pauses: 47 ms, max pause: 5 ms, pauses over 1000 ms: 0
13:31:00, accumulated pauses: 34 ms, max pause: 3 ms, pauses over 1000 ms: 0
13:31:05, accumulated pauses: 23 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:31:10, accumulated pauses: 56 ms, max pause: 8 ms, pauses over 1000 ms: 0
13:31:15, accumulated pauses: 22 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:31:20, accumulated pauses: 105 ms, max pause: 83 ms, pauses over 1000 ms: 0
13:31:25, accumulated pauses: 21 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:31:30, accumulated pauses: 23 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:31:35, accumulated pauses: 22 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:31:40, accumulated pauses: 24 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:31:45, accumulated pauses: 22 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:31:50, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:31:55, accumulated pauses: 43 ms, max pause: 4 ms, pauses over 1000 ms: 0
13:32:00, accumulated pauses: 36 ms, max pause: 3 ms, pauses over 1000 ms: 0
13:32:05, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:32:10, accumulated pauses: 44 ms, max pause: 14 ms, pauses over 1000 ms: 0
13:32:15, accumulated pauses: 29 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:32:20, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:32:25, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:32:30, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:32:35, accumulated pauses: 294 ms, max pause: 281 ms, pauses over 1000 ms: 0
```

### PR DESCRIPTION
**Pull request by jbartok**
Turns out the failures observed in issue #2572 are caused by an exception thrown in `MetricsContext`. It's a NPE caused by non-thread safe data being accessed from multiple threads (one is the thread executing the tasklet, another is the thread doing dynamic metrics collection). This PR attempts to fix the problem.

Fixes #2572 

Checklist:
- [x] Labels and Milestone set

### CODE REVIEW

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/MetricsContext.java [hunk 1]
```diff
@@ -209,4 +177,42 @@ protected long get() {
...
+            metric = metricSupplier.apply(name, unit);
+            threadLocalStore.put(name, metric);
+            threadSafeStore.put(name, metric);
+
+            return metric;
+        }
+
+        void threadSafeForEach(BiConsumer<? super String, ? super AbstractMetric> consumer) {
+            if (threadSafeStore != null) {
+                threadLocalStore.forEach(consumer);
```
Comment (gurbuzali) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/MetricsContext.java:213]: `threadSafeStore.forEach(consumer);` ?

Comment (jbartok) [reply hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/MetricsContext.java:213]: Yeah... copy-paste... Fixing it.

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/MetricsContext.java [hunk 2]
```diff
@@ -50,47 +50,15 @@ Metric threadSafeMetric(String name, Unit unit) {
...
     }
 
     @Override
     public void provideDynamicMetrics(MetricDescriptor tagger, MetricsCollectionContext context) {
-        if (onlyMetric != null) {
-            context.collect(
-                    addUserTag(tagger), onlyName, ProbeLevel.INFO, toProbeUnit(onlyMetric.unit()), onlyMetric.get()
-            );
-        } else if (metrics != null) {
-            MetricDescriptor withUserTag = addUserTag(tagger);
```
Comment (gurbuzali) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/MetricsContext.java:90]: addUserTag(tagger) is not necessary any more

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/MetricsContext.java [hunk 3]
```diff
@@ -209,4 +177,42 @@ protected long get() {
...
     }
 
+    /**
+     * Map for storing metrics on a per name basis. Meant to offer fast,
+     * single-threaded access, but also a loosely consistent, thread safe
+     * way to iterate over the content.
+     */
+    private static class MetricsStore {
+
+        private Map<String, AbstractMetric> threadLocalStore;
```
Comment (gurbuzali) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/MetricsContext.java:187]: we are doubling the memory footprint and complicating the implementation to provide a fast local get. Is this really necessary? does it affect the performance that much to use a single `ConcurrentHashMap` ?

Comment (jbartok) [reply hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/MetricsContext.java:187]: The `metric` method is called for each processed item, so with just using the `ConcurrentHashMap`, the performance impact might be too big. At least that's what I think...

Comment (viliam-durina) [reply hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/metrics/MetricsContext.java:187]: I was curious and suspected that a non-contended read-only CHM might be very similar to plain HM because non-contended volatile read on x86 is as fast as a non-volatile read:
```
Benchmark     Mode  Cnt   Score   Error  Units
ChmBench.chm  avgt   10  21,687 ± 0,122  ns/op
ChmBench.hm   avgt   10  22,610 ± 0,163  ns/op
```
source: 
```java
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@State(Scope.Thread)
@Fork(value = 1, warmups = 1)
@Warmup(iterations = 10)
@Measurement(iterations = 10)
public class ChmBench {

    private final Map<String, Integer> chm = new ConcurrentHashMap<>();
    private final Map<String, Integer> hm = new HashMap<>();

    {
        chm.put("1", 1);
        chm.put("2", 2);
        chm.put("3", 3);

        hm.putAll(chm);
    }

    @Benchmark
    public void chm() {
        chm.get("3");
        chm.get("1");
        chm.get("2");
    }

    @Benchmark
    public void hm() {
        hm.get("3");
        hm.get("1");
        hm.get("2");
    }
}
```
Maybe another CPU will be different, I don't know.

**Review by viliam-durina — APPROVED** [review]

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3618/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3618/jet-oss-pr-builder-3618.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   SqlClientTest.test_jetJobReturnRowsToClientFrom:55 ? HazelcastSql At line 1, c...
[INFO] 
[ERROR] Tests run: 580, Failures: 0, Errors: 1, Skipped: 0
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Review by gurbuzali — APPROVED** [review]

**Comment by jbartok** [comment]
verify

**Comment by jbartok** [comment]
> You could have used `computeIfAbsent()` :)

Yes, but it would have looked like this: `metrics.computeIfAbsent(name, IGNORED -> metricSupplier.apply(name, unit))` and if my understanding of lambdas is not wrong, since this one uses state external to it, there would have been an instance of this lambda created on each call to `computeIfAbsent`, which would have just ended up as garbage, most of the time. That's why I didn't use it. Am I wrong?

**Comment by viliam-durina** [comment]
@jbartok Yes, that's true. But you can extract that lambda to a field, we do that commonly, [e.g. here](https://github.com/hazelcast/hazelcast-jet/blob/aba6b8c3da562ee219b955886183b9647a3259ac/hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/processor/SlidingWindowP.java#L166). The `IGNORED` is common with `computeIfAbsent` - I think I wrote more lambdas where it was ignored than where it was not...

Since this code is single-writer, using `computeIfAbsent` is a very trivial optimization - it avoids two hash map lookups (one when checking and the other when putting). With multiple writers it would ensure that there's no race.

**Comment by jbartok** [comment]
@viliam-durina, thanks, understood. It's indeed a neat trick, when the external states used in the lambda bodies are themselves fields. Not the case here though, `unit` is not really suitable. I suppose I could set up a field where I store it, before calling the lambda... Anyways, good to know, will use it in the future.
