### PR TITLE
Don't interrupt blocking threads when terminating

### LINKED ISSUE #1946: com.hazelcast.jet.impl.connector.JmsIntegrationTest_ActiveMQ.stressTest_exactlyOnce_forceful_durableTopic
_master_ (commit 52fb2b05b94ed28bc1abf0e77db85f796c8c160f)

Failed on IBM JDK 8: http://jenkins.hazelcast.com/job/jet-oss-master-ibm-jdk8/155/testReport/junit/com.hazelcast.jet.impl.connector/JmsIntegrationTest_ActiveMQ/stressTest_exactlyOnce_forceful_durableTopic/

Stacktrace:
```
java.lang.AssertionError: jobId=03dc-e117-b8c4-0001 expected:<RUNNING> but was:<FAILED>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at com.hazelcast.jet.core.JetTestSupport.lambda$assertJobStatusEventually$1(JetTestSupport.java:152)
	at com.hazelcast.jet.core.JetTestSupport$$Lambda$1809.0000000008126930.run(Unknown Source)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1373)
	at com.hazelcast.jet.core.JetTestSupport.assertJobStatusEventually(JetTestSupport.java:151)
	at com.hazelcast.jet.core.JetTestSupport.assertJobStatusEventually(JetTestSupport.java:146)
	at com.hazelcast.jet.impl.connector.JmsIntegrationTestBase.stressTest(JmsIntegrationTestBase.java:477)
	at com.hazelcast.jet.impl.connector.JmsIntegrationTestBase.stressTest_exactlyOnce_forceful_durableTopic(JmsIntegrationTestBase.java:407)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:818)
```

Standard output:
```
02:03:10,002 DEBUG || - [JobExecutionService] hz.modest_keller.jet.cooperative.thread-14 - [127.0.0.1]:5702 [jet] [4.0-SNAPSHOT] Execution of job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c5-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:303)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:588)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:485)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1988)
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:59)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:458)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:392)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:378)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker$$Lambda$998.000000000C835470.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:902)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:346)
	at java.lang.Thread.run(Thread.java:818)
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:225)
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.run(TerminateExecutionOperation.java:61)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:228)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:217)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:433)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:166)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:136)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:123)
02:03:10,003  INFO || - [TransactionContext] hz.gallant_keller.jet.blocking.thread-4 - commit failed for transaction TX:ID:c30cd294d3dc-42959-1581127362428-246:1:1
javax.jms.JMSException: java.io.InterruptedIOException
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:72)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1421)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1436)
	at org.apache.activemq.TransactionContext.commit(TransactionContext.java:330)
	at org.apache.activemq.ActiveMQSession.commit(ActiveMQSession.java:582)
	at com.hazelcast.jet.impl.connector.StreamJmsP.snapshotCommitFinish(StreamJmsP.java:199)
	at com.hazelcast.jet.impl.processor.ProcessorWrapper.snapshotCommitFinish(ProcessorWrapper.java:128)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:335)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:293)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.InterruptedIOException
	at org.apache.activemq.transport.FutureResponse.dealWithInterrupt(FutureResponse.java:63)
	at org.apache.activemq.transport.FutureResponse.getResult(FutureResponse.java:51)
	at org.apache.activemq.transport.ResponseCorrelator.request(ResponseCorrelator.java:87)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1392)
	... 13 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2025)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:414)
	at org.apache.activemq.transport.FutureResponse.getResult(FutureResponse.java:48)
	... 15 more
02:03:10,005  WARN || - [TaskletExecutionService] hz.gallant_keller.jet.blocking.thread-4 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Exception in ProcessorTasklet{jmsTopicSource(?)#1}
javax.jms.JMSException: java.io.InterruptedIOException
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:72)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1421)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1436)
	at org.apache.activemq.TransactionContext.commit(TransactionContext.java:330)
	at org.apache.activemq.ActiveMQSession.commit(ActiveMQSession.java:582)
	at com.hazelcast.jet.impl.connector.StreamJmsP.snapshotCommitFinish(StreamJmsP.java:199)
	at com.hazelcast.jet.impl.processor.ProcessorWrapper.snapshotCommitFinish(ProcessorWrapper.java:128)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:335)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:293)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.InterruptedIOException
	at org.apache.activemq.transport.FutureResponse.dealWithInterrupt(FutureResponse.java:63)
	at org.apache.activemq.transport.FutureResponse.getResult(FutureResponse.java:51)
	at org.apache.activemq.transport.ResponseCorrelator.request(ResponseCorrelator.java:87)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1392)
	... 13 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2025)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:414)
	at org.apache.activemq.transport.FutureResponse.getResult(FutureResponse.java:48)
	... 15 more
02:03:10,005 DEBUG || - [JobExecutionService] hz.gallant_keller.jet.blocking.thread-4 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Execution of job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c5-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:303)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:588)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:485)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1988)
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:59)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:458)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:225)
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.run(TerminateExecutionOperation.java:61)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:228)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:217)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:405)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:432)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:590)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:575)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:534)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:236)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:261)
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:245)
	at com.hazelcast.jet.impl.MasterJobContext.lambda$cancelExecutionInvocations$16(MasterJobContext.java:613)
	at com.hazelcast.jet.impl.MasterJobContext$$Lambda$1742.00000000B4005620.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
02:03:10,005 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-73 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Execution of job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c5-0001 has failures: [[127.0.0.1]:5702=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL, [127.0.0.1]:5701=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL]
02:03:10,006 DEBUG || - [MasterJobContext] hz.gallant_keller.cached.thread-47 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Sending CompleteExecutionOperation for job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c5-0001
02:03:10,006 DEBUG || - [CompleteExecutionOperation] hz.gallant_keller.cached.thread-47 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Completing execution 03dc-e117-b8c5-0001 from caller [127.0.0.1]:5701, error=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
02:03:10,006 DEBUG || - [CompleteExecutionOperation] hz.modest_keller.generic-operation.thread-2 - [127.0.0.1]:5702 [jet] [4.0-SNAPSHOT] Completing execution 03dc-e117-b8c5-0001 from caller [127.0.0.1]:5701, error=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
02:03:10,006 DEBUG || - [JobExecutionService] hz.modest_keller.generic-operation.thread-2 - [127.0.0.1]:5702 [jet] [4.0-SNAPSHOT] Completed execution of job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c5-0001
02:03:10,007 ERROR || - [ExecutionContext] hz.gallant_keller.cached.thread-47 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c5-0001 encountered an exception in ProcessorSupplier.close(), ignoring it
javax.jms.JMSException: Disposed due to prior exception
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:72)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1421)
	at org.apache.activemq.ActiveMQConnection.close(ActiveMQConnection.java:688)
	at com.hazelcast.jet.impl.connector.StreamJmsP$Supplier.close(StreamJmsP.java:289)
	at com.hazelcast.jet.impl.util.WrappingProcessorSupplier.close(WrappingProcessorSupplier.java:57)
	at com.hazelcast.jet.impl.execution.ExecutionContext.completeExecution(ExecutionContext.java:196)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$completeExecution$f4fa789d$1(JobExecutionService.java:346)
	at com.hazelcast.jet.impl.JobExecutionService$$Lambda$1570.00000000DC10D460.runEx(Unknown Source)
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:30)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:407)
	at com.hazelcast.jet.impl.JobExecutionService.completeExecution(JobExecutionService.java:345)
	at com.hazelcast.jet.impl.operation.CompleteExecutionOperation.run(CompleteExecutionOperation.java:89)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:228)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:217)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:405)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:432)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:590)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:575)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:534)
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:236)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:261)
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:245)
	at com.hazelcast.jet.impl.MasterJobContext.lambda$invokeCompleteExecution$12(MasterJobContext.java:577)
	at com.hazelcast.jet.impl.MasterJobContext$$Lambda$1567.000000002C005C60.run(Unknown Source)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$42(JobCoordinationService.java:978)
	at com.hazelcast.jet.impl.JobCoordinationService$$Lambda$1163.00000000285CE080.call(Unknown Source)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$43(JobCoordinationService.java:997)
	at com.hazelcast.jet.impl.JobCoordinationService$$Lambda$1164.00000000285CE430.call(Unknown Source)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: org.apache.activemq.transport.TransportDisposedIOException: Disposed due to prior exception
	at org.apache.activemq.transport.ResponseCorrelator.onException(ResponseCorrelator.java:125)
	at org.apache.activemq.transport.FutureResponse.dealWithInterrupt(FutureResponse.java:67)
	at org.apache.activemq.transport.FutureResponse.getResult(FutureResponse.java:51)
	at org.apache.activemq.transport.ResponseCorrelator.request(ResponseCorrelator.java:87)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1392)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1436)
	at org.apache.activemq.TransactionContext.commit(TransactionContext.java:330)
	at org.apache.activemq.ActiveMQSession.commit(ActiveMQSession.java:582)
	at com.hazelcast.jet.impl.connector.StreamJmsP.snapshotCommitFinish(StreamJmsP.java:199)
	at com.hazelcast.jet.impl.processor.ProcessorWrapper.snapshotCommitFinish(ProcessorWrapper.java:128)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:335)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:293)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.InterruptedIOException
	at org.apache.activemq.transport.FutureResponse.dealWithInterrupt(FutureResponse.java:63)
	... 16 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2025)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:414)
	at org.apache.activemq.transport.FutureResponse.getResult(FutureResponse.java:48)
	... 15 more
02:03:10,008 DEBUG || - [JobExecutionService] hz.gallant_keller.cached.thread-47 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Completed execution of job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c5-0001
02:03:10,011  INFO || - [MasterJobContext] hz.gallant_keller.cached.thread-47 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] About to restore the state of job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c6-0001 from snapshot 4, mapName = __jet.snapshot.03dc-e117-b8c4-0001.0
02:03:10,011  INFO || - [MasterJobContext] hz.gallant_keller.cached.thread-47 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Start executing job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c6-0001, execution graph in DOT format:
digraph DAG {
	"jmsTopicSource(?)" [localParallelism=1];
	"map-stateful-global" [localParallelism=1];
	"loggerSink" [localParallelism=1];
	"jmsTopicSource(?)" -> "map-stateful-global" [label="distributed-partitioned", queueSize=1024];
	"map-stateful-global" -> "loggerSink" [queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
02:03:10,011 DEBUG || - [MasterJobContext] hz.gallant_keller.cached.thread-47 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Building execution plan for job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c6-0001
02:03:10,012 DEBUG || - [MasterJobContext] hz.gallant_keller.cached.thread-47 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Built execution plans for job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c6-0001
02:03:10,013 DEBUG || - [InitExecutionOperation] hz.modest_keller.generic-operation.thread-4 - [127.0.0.1]:5702 [jet] [4.0-SNAPSHOT] Initializing execution plan for job 03dc-e117-b8c4-0001, execution 03dc-e117-b8c6-0001 from [127.0.0.1]:5701
02:03:10,013 DEBUG || - [InitExecutionOperation] hz.gallant_keller.cached.thread-47 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Initializing execution plan for job 03dc-e117-b8c4-0001, execution 03dc-e117-b8c6-0001 from [127.0.0.1]:5701
02:03:10,016  INFO || - [FailoverTransport] ActiveMQ Task-1 - Successfully connected to vm://embedded-broker?create=false
02:03:10,017  INFO || - [JobExecutionService] hz.modest_keller.generic-operation.thread-4 - [127.0.0.1]:5702 [jet] [4.0-SNAPSHOT] Execution plan for jobId=03dc-e117-b8c4-0001, jobName='03dc-e117-b8c4-0001', executionId=03dc-e117-b8c6-0001 initialized
02:03:10,033  WARN || - [Transport] Async Exception Handler - Transport Connection to: vm://embedded-broker#242 failed: org.apache.activemq.transport.TransportDisposedIOException: Peer (vm://embedded-broker#242) disposed.
02:03:10,048  WARN || - [TransportConnection] ActiveMQ VMTransport: vm://embedded-broker#247-1 - Failed to add Connection id=ID:c30cd294d3dc-42959-1581127362428-250:1, clientId=foo-client-id due to {}
javax.jms.InvalidClientIDException: Broker: embedded-broker - Client: foo-client-id already connected from vm://embedded-broker#242
	at org.apache.activemq.broker.region.RegionBroker.addConnection(RegionBroker.java:247)
	at org.apache.activemq.broker.jmx.ManagedRegionBroker.addConnection(ManagedRegionBroker.java:227)
	at org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:99)
	at org.apache.activemq.advisory.AdvisoryBroker.addConnection(AdvisoryBroker.java:119)
	at org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:99)
	at org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:99)
	at org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:99)
	at org.apache.activemq.broker.TransportConnection.processAddConnection(TransportConnection.java:849)
	at org.apache.activemq.command.ConnectionInfo.visit(ConnectionInfo.java:139)
	at org.apache.activemq.broker.TransportConnection.service(TransportConnection.java:336)
	at org.apache.activemq.broker.TransportConnection$1.onCommand(TransportConnection.java:200)
	at org.apache.activemq.transport.ResponseCorrelator.onCommand(ResponseCorrelator.java:116)
	at org.apache.activemq.transport.MutexTransport.onCommand(MutexTransport.java:50)
	at org.apache.activemq.transport.vm.VMTransport.iterate(VMTransport.java:275)
	at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133)
	at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)
02:03:10,049 ERROR || - [InitExecutionOperation] hz.gallant_keller.cached.thread-47 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Broker: embedded-broker - Client: foo-client-id already connected from vm://embedded-broker#242
javax.jms.InvalidClientIDException: Broker: embedded-broker - Client: foo-client-id already connected from vm://embedded-broker#242
	at org.apache.activemq.broker.region.RegionBroker.addConnection(RegionBroker.java:247)
	at org.apache.activemq.broker.jmx.ManagedRegionBroker.addConnection(ManagedRegionBroker.java:227)
	at org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:99)
	at org.apache.activemq.advisory.AdvisoryBroker.addConnection(AdvisoryBroker.java:119)
	at org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:99)
	at org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:99)
	at org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:99)
	at org.apache.activemq.broker.TransportConnection.processAddConnection(TransportConnection.java:849)
	at org.apache.activemq.command.ConnectionInfo.visit(ConnectionInfo.java:139)
	at org.apache.activemq.broker.TransportConnection.service(TransportConnection.java:336)
	at org.apache.activemq.broker.TransportConnection$1.onCommand(TransportConnection.java:200)
	at org.apache.activemq.transport.ResponseCorrelator.onCommand(ResponseCorrelator.java:116)
	at org.apache.activemq.transport.MutexTransport.onCommand(MutexTransport.java:50)
	at org.apache.activemq.transport.vm.VMTransport.iterate(VMTransport.java:275)
	at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133)
	at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)
02:03:10,049 DEBUG || - [MasterJobContext] hz.gallant_keller.cached.thread-64 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Init of job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c6-0001 has failures: [[127.0.0.1]:5701=javax.jms.InvalidClientIDException: Broker: embedded-broker - Client: foo-client-id already connected from vm://embedded-broker#242]
02:03:10,049 DEBUG || - [MasterJobContext] hz.gallant_keller.cached.thread-64 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Sending CompleteExecutionOperation for job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c6-0001
02:03:10,051 DEBUG || - [CompleteExecutionOperation] hz.gallant_keller.cached.thread-64 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Completing execution 03dc-e117-b8c6-0001 from caller [127.0.0.1]:5701, error=javax.jms.InvalidClientIDException: Broker: embedded-broker - Client: foo-client-id already connected from vm://embedded-broker#242
02:03:10,051 DEBUG || - [JobExecutionService] hz.gallant_keller.cached.thread-64 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Completed execution of job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c6-0001
02:03:10,051 DEBUG || - [CompleteExecutionOperation] hz.modest_keller.generic-operation.thread-7 - [127.0.0.1]:5702 [jet] [4.0-SNAPSHOT] Completing execution 03dc-e117-b8c6-0001 from caller [127.0.0.1]:5701, error=javax.jms.InvalidClientIDException: Broker: embedded-broker - Client: foo-client-id already connected from vm://embedded-broker#242
02:03:10,052 DEBUG || - [JobExecutionService] hz.modest_keller.generic-operation.thread-7 - [127.0.0.1]:5702 [jet] [4.0-SNAPSHOT] Completed execution of job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c6-0001
02:03:10,052 DEBUG || - [MasterSnapshotContext] hz.gallant_keller.cached.thread-64 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Not beginning snapshot, job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c6-0001 is not RUNNING, but STARTING
02:03:10,052 ERROR || - [MasterJobContext] hz.gallant_keller.cached.thread-47 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Execution of job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c6-0001 failed
	Start time: 2020-02-08T02:03:10.008
	Duration: 44 ms
	For further details enable JobConfig.storeMetricsAfterJobCompletion
javax.jms.InvalidClientIDException: Broker: embedded-broker - Client: foo-client-id already connected from vm://embedded-broker#242
	at org.apache.activemq.broker.region.RegionBroker.addConnection(RegionBroker.java:247)
	at org.apache.activemq.broker.jmx.ManagedRegionBroker.addConnection(ManagedRegionBroker.java:227)
	at org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:99)
	at org.apache.activemq.advisory.AdvisoryBroker.addConnection(AdvisoryBroker.java:119)
	at org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:99)
	at org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:99)
	at org.apache.activemq.broker.BrokerFilter.addConnection(BrokerFilter.java:99)
	at org.apache.activemq.broker.TransportConnection.processAddConnection(TransportConnection.java:849)
	at org.apache.activemq.command.ConnectionInfo.visit(ConnectionInfo.java:139)
	at org.apache.activemq.broker.TransportConnection.service(TransportConnection.java:336)
	at org.apache.activemq.broker.TransportConnection$1.onCommand(TransportConnection.java:200)
	at org.apache.activemq.transport.ResponseCorrelator.onCommand(ResponseCorrelator.java:116)
	at org.apache.activemq.transport.MutexTransport.onCommand(MutexTransport.java:50)
	at org.apache.activemq.transport.vm.VMTransport.iterate(VMTransport.java:275)
	at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133)
	at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)
02:03:10,052  WARN || - [TransportConnection] ActiveMQ VMTransport: vm://embedded-broker#243-1 - no matching consumer, ignoring ack null
02:03:10,053 DEBUG || - [JobCoordinationService] hz.gallant_keller.cached.thread-47 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] job '03dc-e117-b8c4-0001', execution 03dc-e117-b8c6-0001 is completed
02:03:12,049  INFO || - [TransportConnection] ActiveMQ BrokerService[embedded-broker] Task-5 - Stopping vm://embedded-broker#246 because Failed with SecurityException: Broker: embedded-broker - Client: foo-client-id already connected from vm://embedded-broker#242
02:03:12,049  WARN || - [FailoverTransport] ActiveMQ BrokerService[embedded-broker] Task-1 - Transport (vm://embedded-broker?create=false) failed , attempting to automatically reconnect: {}
org.apache.activemq.transport.TransportDisposedIOException: peer (vm://embedded-broker#247) stopped.
	at org.apache.activemq.transport.vm.VMTransport.stop(VMTransport.java:233)
	at org.apache.activemq.transport.TransportFilter.stop(TransportFilter.java:72)
	at org.apache.activemq.transport.TransportFilter.stop(TransportFilter.java:72)
	at org.apache.activemq.transport.ResponseCorrelator.stop(ResponseCorrelator.java:132)
	at org.apache.activemq.broker.TransportConnection.doStop(TransportConnection.java:1194)
	at org.apache.activemq.broker.TransportConnection$4.run(TransportConnection.java:1160)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)
02:03:12,062  INFO || - [FailoverTransport] ActiveMQ Task-2 - Successfully reconnected to vm://embedded-broker?create=false
02:03:13,347 DEBUG || - [JobRepository] hz.gallant_keller.cached.thread-6 - [127.0.0.1]:5701 [jet] [4.0-SNAPSHOT] Deleting snapshot data map '__jet.snapshot.03dc-e117-b8c4-0001.1' because job already finished
```

### PR DESCRIPTION
**Pull request by viliam-durina**
All processors are required to not block for extended time, the
interrupt isn't needed. It can make the execution termination faster,
but we've had issues with interrupted threads in the past. The latest
instance is in #1946 where the ApacheMQ client, when interrupted during
a commit, subsequently failed at `Connection.close()` which then leaked
the connection. And in the case of a durable subscriber the job couldn't
start again because the client ID was duplicate.

Fixes #1946

Checklist
- [x] Tags Set
- [x] Milestone Set
- [x] Any breaking changes are documented
- [x] New public APIs have `@Nonnull/@Nullable` annotations
- [x] New public APIs have `@since` tags in Javadoc
- [x] For code samples, code sample main readme is updated

### CODE REVIEW

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Processor.java [hunk 1]
```diff
@@ -99,24 +99,34 @@
...
-     * <p>
-     * If this processor declares itself cooperative, it will share a thread
-     * with other cooperative processors. Otherwise it will run in a dedicated
-     * Java thread.
+     * multithreading. If this processor declares itself cooperative, it will
+     * share a thread with other cooperative processors. Otherwise it will run
+     * in a dedicated Java thread.
+     * <p>
+     * There are specific requirements that all <em>processing methods</em> of
+     * a cooperative processor must follow:<ul>
```
Comment (cangencer) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/core/Processor.java]: can you fix the formatting here? looks weird? See for example on `Jet.bootstrappedInstance`
