### PR TITLE
Fix session window early results test

### LINKED ISSUE #1260: com.hazelcast.jet.pipeline.WindowGroupAggregateTest.sessionWindow_withEarlyResults[1: mode=client]
http://jenkins.hazelcast.com/job/Jet-pr-builder/69/testReport/junit/com.hazelcast.jet.pipeline/WindowGroupAggregateTest/sessionWindow_withEarlyResults_1__mode_client_/

```
expected:<... 30)
(006, b, 30)
(0[12, a, 54)
(012, b, 54)
(018, a, 78)
(018, b, 78)
(024, a, 102)
(024, b, 102)
(030, a, 126)
(030, b, 126)
(036, a, 150)
(036, b, 150)
(042, a, 174)
(042, b, 174)
(048, a, 198)
(048, b, 198)
(054, a, 222)
(054, b, 222)
(060, a, 246)
(060, b, 246)
(066, a, 270)
(066, b, 270)
(072, a, 294)
(072, b, 294)
(078, a, 318)
(078, b, 318)
(084, a, 342)
(084, b, 342)
(090, a, 366)
(090, b, 366])> but was:<... 30)
(006, b, 30)
(0[07, a, 24)
(007, b, 24)
(012, a, 54)
(012, b, 54)
(013, a, 42)
(013, b, 42)
(018, a, 78)
(018, b, 78)
(019, a, 60)
(019, b, 60)
(024, a, 102)
(024, b, 102)
(025, a, 78)
(025, b, 78)
(030, a, 126)
(030, b, 126)
(031, a, 96)
(031, b, 96)
(036, a, 150)
(036, b, 150)
(037, a, 114)
(037, b, 114)
(042, a, 174)
(042, b, 174)
(043, a, 87)
(043, b, 87)
(048, a, 198)
(048, b, 198)
(049, a, 150)
(049, b, 150)
(054, a, 222)
(054, b, 222)
(055, a, 168)
(055, b, 168)
(060, a, 246)
(060, b, 246)
(061, a, 186)
(061, b, 186)
(066, a, 270)
(066, b, 270)
(067, a, 135)
(067, b, 135)
(072, a, 294)
(072, b, 294)
(073, a, 222)
(073, b, 222)
(078, a, 318)
(078, b, 318)
(079, a, 159)
(079, b, 159)
(084, a, 342)
(084, b, 342)
(085, a, 258)
(085, b, 258)
(090, a, 366)
(090, b, 366)
(091, a, 183)
(091, b, 183])>```

### PR DESCRIPTION
**Pull request by mtopolnik**
Fixes #1260

### CODE REVIEW

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/WindowGroupAggregateTest.java [hunk 1]
```diff
@@ -287,35 +287,40 @@ private void testSessionWindow(long earlyResultsPeriod) {
...
+                        ? null
+                        : new TimestampedEntry<>(start, key, sum))
+                .drainTo(sink);
         jet().newJob(p);
 
         Stream<TimestampedEntry<String, Long>> expectedStream = input
                 .stream()
                 .map(i -> (long) i - i % (sessionLength + sessionTimeout))
                 .distinct()
+                .filter(start -> start != 0)
```
Comment (viliam-durina) [inline hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/WindowGroupAggregateTest.java]: Should have been `FILTERED_OUT_WINDOW_START` instead of `0` here.

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/WindowGroupAggregateTest.java [hunk 2]
```diff
@@ -287,35 +287,40 @@ private void testSessionWindow(long earlyResultsPeriod) {
...
+        StageWithKeyAndWindow<Entry<String, Integer>, String> windowed = fx
+                .stage0()
+                .window(session(sessionTimeout).setEarlyResultsPeriod(earlyResultsPeriod))
+                .groupingKey(Entry::getKey);
 
         // Then
-        aggregated.drainTo(sink);
+
+        windowed.aggregate(summingLong(Entry::getValue), (start, end, key, sum) ->
+                (start == FILTERED_OUT_WINDOW_START || (emittingEarlyResults && end - start != sessionLength + 1))
```
Comment (viliam-durina) [inline hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/WindowGroupAggregateTest.java]: Why do you filter out results with just single event?

Comment (mtopolnik) [reply hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/WindowGroupAggregateTest.java]: I filter out all window results that are missing some events
