### PR TITLE
Change invocation builder to send invocation to master member instead…

### LINKED ISSUE #1128: Non-smart client cannot submit a job if it connects to a non-master member
```
Job 0c50-8223-aa06-42f2 (name ??) failed because it has received a non-restartable exception during submission
com.hazelcast.jet.JetException: Cannot submit job 0c50-8223-aa06-42f2 from non-master node.
```

### PR DESCRIPTION
**Pull request by eminn**
… of connected member in case of non-smart client

Fixes #1128

### CODE REVIEW

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/deployment/ClientJobSubmissionTest.java [hunk 1]
```diff
@@ -0,0 +1,187 @@
...
+
+import java.util.List;
+
+import static org.junit.Assert.assertEquals;
+import static org.junit.Assert.assertFalse;
+import static org.junit.Assert.assertNotNull;
+import static org.junit.Assert.assertTrue;
+
+@RunWith(HazelcastSerialClassRunner.class)
+public class ClientJobSubmissionTest extends JetTestSupport {
```
Comment (cangencer) [inline hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/deployment/ClientJobSubmissionTest.java]: would be better called "NonsmartClientTest"

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/deployment/ClientJobSubmissionTest.java [hunk 2]
```diff
@@ -0,0 +1,187 @@
...
+        ClientConfig clientConfig = new ClientConfig();
+        clientConfig.getNetworkConfig().setSmartRouting(false);
+        clientConfig.getGroupConfig().setName(jetConfig.getHazelcastConfig().getGroupConfig().getName());
+        clientConfig.getNetworkConfig().getAddresses().clear();
+        clientConfig.getNetworkConfig().getAddresses().add(address.getHost() + ":" + address.getPort());
+        client = createJetClient(clientConfig);
+    }
+
+    @Test
+    public void Given_nonSmartClient_When_jobSubmitted_Then_executedSuccessfully() {
```
Comment (cangencer) [inline hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/deployment/ClientJobSubmissionTest.java]: naming should be `when_.._then_..`

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/deployment/ClientJobSubmissionTest.java [hunk 3]
```diff
@@ -0,0 +1,187 @@
...
+        assertEquals(10, instance.getList(sinkName).size());
+    }
+
+    @Test
+    public void Given_nonSmartClient_When_jobSubmitted_Then_jobCanBeFetchedByIdOrName() {
+        //Given
+        String jobName = randomName();
+
+        //When
+        Pipeline p = Pipeline.create();
```
Comment (cangencer) [inline hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/deployment/ClientJobSubmissionTest.java]: I would refactor the pipeline to a common method since it's used in a lot of the tests

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java [hunk 4]
```diff
@@ -125,6 +134,19 @@ protected static File createTempDirectory() throws IOException {
...
     }
 
+    public static void assertJobStatusEventually(Job job, JobStatus expected) {
+        assertJobStatusEventually(job, expected, 10);
+
+    }
+
+    public static void assertJobStatusEventually(Job job, JobStatus expected, int timeoutSeconds) {
+        assertTrueEventually(() -> {
+            assertNotNull(job);
```
Comment (cangencer) [inline hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java]: what's the point of the null check here?

Comment (eminn) [reply hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java]: Yes, you are right I'll pull that out of the block.

Comment (eminn) [reply hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JetTestSupport.java]: https://github.com/hazelcast/hazelcast-jet/pull/1136
