### PR TITLE
Fixed issue with the unzipping the nested directories.

### LINKED ISSUE #1845: java.nio.file.FileAlreadyExistsException when unzipping a directory with nested directories
```
Caused by: java.nio.file.FileAlreadyExistsException: /var/folders/7x/p5jb54yj5sx_8b748d8kn3780000gn/T/jet-festive_lehmann-03b6-aa37-8c40-0001-data7827145962632219873/model
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:727)
	at com.hazelcast.jet.impl.util.IOUtil.unzip(IOUtil.java:123)
	at com.hazelcast.jet.impl.execution.init.Contexts$ProcSupplierCtx.extractFileToDisk(Contexts.java:189)
```

### PR DESCRIPTION
**Pull request by eminn**
The issue is related to the ZIP entries are not being correctly created for the directories which doesn't include a trailing slash so it leads to ZipEntry.isDirectory() calls to always return false.

Checklist
- [x] Tags Set
- [x] Milestone Set
- [x] Any breaking changes are documented
- [x] New public APIs have `@Nonnull/@Nullable` annotations
- [x] New public APIs have `@since` tags in Javadoc
- [x] For code samples, code sample main readme is updated

Links to issues fixed (if any):

Fixes #1845

### CODE REVIEW

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/IOUtilTest.java [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+    @Rule
+    public TemporaryFolder temporaryFolder = new TemporaryFolder();
+
+    @Test
+    public void test_zipAndUnzipNestedFolder_then_contentsShouldBeSame() throws Exception {
+        //Given
+        ByteArrayOutputStream baos = new ByteArrayOutputStream(1000);
+
+        //When
+        Path originalPath = Paths.get(this.getClass().getResource("/nested").toURI());
```
Comment (viliam-durina) [inline hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/IOUtilTest.java]: IIUIC, git also doesn't store empty directories. If you had an empty directory in `/nested`, they aren't there when you check out from git.

Comment (eminn) [reply hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/IOUtilTest.java]: Nope, there wasn't an empty directory under `/nested` folder

Comment (viliam-durina) [reply hazelcast-jet-core/src/test/java/com/hazelcast/jet/impl/util/IOUtilTest.java]: We should test empty directories though
