### PR TITLE
Fix CDC network related test timeouts (issue #2531)

### LINKED ISSUE #2531: com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest timeout issues
Failed on PR builder with nightly tests: http://jenkins.hazelcast.com/job/jet-oss-pr-builder-nightly-tests/5/testReport/

Following test failed due to timeout issues. It should not be caused by changes in the PR:
- `com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringSnapshotting[fail]`
- `com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest`

Stacktrace for `when_databaseShutdownDuringSnapshotting`:
```
org.junit.runners.model.TestTimedOutException: test timed out after 600000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1947)
	at com.hazelcast.jet.Job.join(Job.java:155)
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest$$Lambda$2181/247491064.call(Unknown Source)
	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:750)
	at org.assertj.core.api.Assertions.catchThrowable(Assertions.java:1179)
	at org.assertj.core.api.Assertions.assertThatThrownBy(Assertions.java:1051)
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringSnapshotting(MySqlCdcNetworkIntegrationTest.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Hiccups measured while running test 'when_databaseShutdownDuringSnapshotting[fail](com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest):'
09:47:25, accumulated pauses: 53 ms, max pause: 3 ms, pauses over 1000 ms: 0
09:47:30, accumulated pauses: 60 ms, max pause: 4 ms, pauses over 1000 ms: 0
09:47:35, accumulated pauses: 49 ms, max pause: 4 ms, pauses over 1000 ms: 0
09:47:40, accumulated pauses: 92 ms, max pause: 25 ms, pauses over 1000 ms: 0
09:47:45, accumulated pauses: 41 ms, max pause: 2 ms, pauses over 1000 ms: 0
09:47:50, accumulated pauses: 68 ms, max pause: 10 ms, pauses over 1000 ms: 0
09:47:55, accumulated pauses: 52 ms, max pause: 5 ms, pauses over 1000 ms: 0
09:48:00, accumulated pauses: 22 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:48:05, accumulated pauses: 21 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:48:10, accumulated pauses: 21 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:48:15, accumulated pauses: 21 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:48:20, accumulated pauses: 21 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:48:25, accumulated pauses: 48 ms, max pause: 23 ms, pauses over 1000 ms: 0
09:48:30, accumulated pauses: 23 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:48:35, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:48:40, accumulated pauses: 27 ms, max pause: 4 ms, pauses over 1000 ms: 0
09:48:45, accumulated pauses: 42 ms, max pause: 4 ms, pauses over 1000 ms: 0
09:48:50, accumulated pauses: 32 ms, max pause: 5 ms, pauses over 1000 ms: 0
09:48:55, accumulated pauses: 26 ms, max pause: 3 ms, pauses over 1000 ms: 0
09:49:00, accumulated pauses: 40 ms, max pause: 16 ms, pauses over 1000 ms: 0
09:49:05, accumulated pauses: 22 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:49:10, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:49:15, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:49:20, accumulated pauses: 25 ms, max pause: 2 ms, pauses over 1000 ms: 0
09:49:25, accumulated pauses: 23 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:49:30, accumulated pauses: 23 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:49:35, accumulated pauses: 47 ms, max pause: 20 ms, pauses over 1000 ms: 0
09:49:40, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:49:45, accumulated pauses: 30 ms, max pause: 3 ms, pauses over 1000 ms: 0
09:49:50, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:49:55, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:50:00, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:50:05, accumulated pauses: 42 ms, max pause: 15 ms, pauses over 1000 ms: 0
09:50:10, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:50:15, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:50:20, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:50:25, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:50:30, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:50:35, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:50:40, accumulated pauses: 35 ms, max pause: 9 ms, pauses over 1000 ms: 0
09:50:45, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:50:50, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:50:55, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:51:00, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:51:05, accumulated pauses: 26 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:51:10, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:51:15, accumulated pauses: 45 ms, max pause: 19 ms, pauses over 1000 ms: 0
09:51:20, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:51:25, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:51:30, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:51:35, accumulated pauses: 29 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:51:40, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:51:45, accumulated pauses: 32 ms, max pause: 4 ms, pauses over 1000 ms: 0
09:51:50, accumulated pauses: 34 ms, max pause: 9 ms, pauses over 1000 ms: 0
09:51:55, accumulated pauses: 27 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:52:00, accumulated pauses: 28 ms, max pause: 3 ms, pauses over 1000 ms: 0
09:52:05, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:52:10, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:52:15, accumulated pauses: 27 ms, max pause: 2 ms, pauses over 1000 ms: 0
09:52:20, accumulated pauses: 33 ms, max pause: 2 ms, pauses over 1000 ms: 0
09:52:25, accumulated pauses: 37 ms, max pause: 8 ms, pauses over 1000 ms: 0
09:52:30, accumulated pauses: 133 ms, max pause: 6 ms, pauses over 1000 ms: 0
09:52:35, accumulated pauses: 278 ms, max pause: 31 ms, pauses over 1000 ms: 0
09:52:40, accumulated pauses: 123 ms, max pause: 4 ms, pauses over 1000 ms: 0
09:52:45, accumulated pauses: 209 ms, max pause: 25 ms, pauses over 1000 ms: 0
09:52:50, accumulated pauses: 268 ms, max pause: 11 ms, pauses over 1000 ms: 0
09:52:55, accumulated pauses: 192 ms, max pause: 16 ms, pauses over 1000 ms: 0
09:53:00, accumulated pauses: 66 ms, max pause: 12 ms, pauses over 1000 ms: 0
09:53:05, accumulated pauses: 46 ms, max pause: 3 ms, pauses over 1000 ms: 0
09:53:10, accumulated pauses: 94 ms, max pause: 7 ms, pauses over 1000 ms: 0
09:53:15, accumulated pauses: 44 ms, max pause: 3 ms, pauses over 1000 ms: 0
09:53:20, accumulated pauses: 34 ms, max pause: 2 ms, pauses over 1000 ms: 0
09:53:25, accumulated pauses: 23 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:53:30, accumulated pauses: 23 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:53:35, accumulated pauses: 23 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:53:40, accumulated pauses: 35 ms, max pause: 9 ms, pauses over 1000 ms: 0
09:53:45, accumulated pauses: 30 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:53:50, accumulated pauses: 26 ms, max pause: 2 ms, pauses over 1000 ms: 0
09:53:55, accumulated pauses: 27 ms, max pause: 2 ms, pauses over 1000 ms: 0
09:54:00, accumulated pauses: 41 ms, max pause: 5 ms, pauses over 1000 ms: 0
09:54:05, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:54:10, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:54:15, accumulated pauses: 29 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:54:20, accumulated pauses: 37 ms, max pause: 10 ms, pauses over 1000 ms: 0
09:54:25, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:54:30, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:54:35, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:54:40, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:54:45, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:54:50, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:54:55, accumulated pauses: 36 ms, max pause: 11 ms, pauses over 1000 ms: 0
09:55:00, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:55:05, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:55:10, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:55:15, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:55:20, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:55:25, accumulated pauses: 28 ms, max pause: 2 ms, pauses over 1000 ms: 0
09:55:30, accumulated pauses: 27 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:55:35, accumulated pauses: 38 ms, max pause: 10 ms, pauses over 1000 ms: 0
09:55:40, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:55:45, accumulated pauses: 29 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:55:50, accumulated pauses: 24 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:55:55, accumulated pauses: 27 ms, max pause: 2 ms, pauses over 1000 ms: 0
09:56:00, accumulated pauses: 29 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:56:05, accumulated pauses: 31 ms, max pause: 2 ms, pauses over 1000 ms: 0
09:56:10, accumulated pauses: 23 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:56:15, accumulated pauses: 41 ms, max pause: 13 ms, pauses over 1000 ms: 0
09:56:20, accumulated pauses: 22 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:56:25, accumulated pauses: 23 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:56:30, accumulated pauses: 29 ms, max pause: 3 ms, pauses over 1000 ms: 0
09:56:35, accumulated pauses: 43 ms, max pause: 5 ms, pauses over 1000 ms: 0
09:56:40, accumulated pauses: 43 ms, max pause: 5 ms, pauses over 1000 ms: 0
09:56:45, accumulated pauses: 28 ms, max pause: 3 ms, pauses over 1000 ms: 0
09:56:50, accumulated pauses: 30 ms, max pause: 2 ms, pauses over 1000 ms: 0
09:56:55, accumulated pauses: 27 ms, max pause: 2 ms, pauses over 1000 ms: 0
09:57:00, accumulated pauses: 34 ms, max pause: 3 ms, pauses over 1000 ms: 0
09:57:05, accumulated pauses: 29 ms, max pause: 3 ms, pauses over 1000 ms: 0
09:57:10, accumulated pauses: 27 ms, max pause: 3 ms, pauses over 1000 ms: 0
09:57:15, accumulated pauses: 27 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:57:20, accumulated pauses: 23 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:57:25, accumulated pauses: 177 ms, max pause: 156 ms, pauses over 1000 ms: 0
```

### PR DESCRIPTION
**Pull request by jbartok**
The CDC Network tests are not entirely deterministic. For example when we want to test some behaviour during snapshotting mode we rely on timeouts to do a certain action hopefully in that time period, which succeeds most of the time, but not always. This is ok (or better than no tests at all), but we need to make sure to not trigger false positive failures, when we are not in the targeted test state. 

Current pull request addresses a situation where the MySQL connector's internal reconnect mechanism kicks in and tries to reconnect endlessly, instead of our own reconnect mechanism which would throw an error instead.

Fixes #2531

### CODE REVIEW

File: extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java [hunk 1]
```diff
@@ -407,4 +404,27 @@ private static int findRandomOpenPortInRange(int fromInclusive, int toExclusive)
...
+            if (lenient) {
+                //ignore the timeout; not all tests are deterministic, sometimes we don't end up in the state
+                //we actually want to test
+            } else {
+                fail("Connection failure not thrown");
+            }
+        } catch (ExecutionException ee) {
+            //job completed exceptionally, as expected, we check the details of it
+            Throwable rootCause = Throwables.getRootCause(ee);
+            assertEquals(JetException.class, rootCause.getClass());
```
Comment (frant-hartm) [inline extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java:425]: Better to use 

https://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/AbstractThrowableAssert.html#hasRootCauseInstanceOf(java.lang.Class)

than a shaded package `org.testcontainers.shaded.com.google.common.base.Throwables` from testcontainers

**Review by frant-hartm — APPROVED** [review]
