### PR TITLE
Fix MySql related intermittent network test failures (issue #2534)

### LINKED ISSUE #2534: com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringBinlogReading[fail]
_master_ (commit 7132dae97adf8b2b19df4676f9da5e6e04a6831e)

Failed on Sonar nightly build: http://jenkins.hazelcast.com/job/jet-oss-master-sonar-nightly/622/testReport/junit/com.hazelcast.jet.cdc.mysql/MySqlCdcNetworkIntegrationTest/when_databaseShutdownDuringBinlogReading_fail_/

Stacktrace:
```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.initMySql(MySqlCdcNetworkIntegrationTest.java:355)
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringBinlogReading(MySqlCdcNetworkIntegrationTest.java:258)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
	... 15 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:498)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 16 more
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"driver failed programming external connectivity on endpoint reverent_kapitsa (9f4ec07388a040814fdf1f40c9dc328bdfe395b01f431acd1ce975863144a471): Error starting userland proxy: listen tcp 0.0.0.0:40708: bind: address already in use"}

	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:293)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271)
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:116)
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testcontainers.dockerclient.AuditLoggingDockerClient.lambda$wrappedCommand$14(AuditLoggingDockerClient.java:102)
	at com.sun.proxy.$Proxy45.exec(Unknown Source)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:419)
	... 18 more
```

Standard output:
```
2020-09-20 13:40:31,368 [ INFO] [when_databaseShutdownDuringBinlogReading] [o.t.d.DockerClientProviderStrategy]: Loaded org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy from ~/.testcontainers.properties, will try it first
2020-09-20 13:40:32,130 [ INFO] [when_databaseShutdownDuringBinlogReading] [o.t.d.EnvironmentAndSystemPropertyClientProviderStrategy]: Found docker client settings from environment
2020-09-20 13:40:32,131 [ INFO] [when_databaseShutdownDuringBinlogReading] [o.t.d.DockerClientProviderStrategy]: Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=unix:///var/run/docker.sock
2020-09-20 13:40:32,362 [ INFO] [when_databaseShutdownDuringBinlogReading] [o.t.DockerClientFactory]: Docker host IP address is 172.17.0.1
2020-09-20 13:40:32,394 [ INFO] [when_databaseShutdownDuringBinlogReading] [o.t.DockerClientFactory]: Connected to docker: 
  Server Version: 18.06.1-ce
  API Version: 1.38
  Operating System: Red Hat Enterprise Linux
  Total Memory: 386667 MB
2020-09-20 13:40:32,536 [ WARN] [when_databaseShutdownDuringBinlogReading] [o.t.u.RegistryAuthLocator]: Failure when attempting to lookup auth config (dockerImageName: testcontainersofficial/ryuk:0.3.0, configFile: /home/jenkins/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /home/jenkins/.docker/config.json (No such file or directory)
2020-09-20 13:40:33,659 [ INFO] [when_databaseShutdownDuringBinlogReading] [o.t.DockerClientFactory]: Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
2020-09-20 13:40:33,659 [ INFO] [when_databaseShutdownDuringBinlogReading] [o.t.DockerClientFactory]: Checking the system...
2020-09-20 13:40:33,660 [ INFO] [when_databaseShutdownDuringBinlogReading] [o.t.DockerClientFactory]: ?? Docker server version should be at least 1.6.0
2020-09-20 13:40:33,752 [ INFO] [when_databaseShutdownDuringBinlogReading] [o.t.DockerClientFactory]: ?? Docker environment should have more than 2GB free disk space
2020-09-20 13:40:33,897 [ INFO] [when_databaseShutdownDuringBinlogReading] [d.2]]: Creating container for image: debezium/example-mysql:1.2
2020-09-20 13:40:34,632 [ INFO] [when_databaseShutdownDuringBinlogReading] [d.2]]: Starting container with ID: a09f6c19aae64ebfe1ba03092734383cc2acd1528cdc84c3ff5b09ac72a25782
2020-09-20 13:40:34,865 [ERROR] [when_databaseShutdownDuringBinlogReading] [d.2]]: Could not start container
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"driver failed programming external connectivity on endpoint gracious_kapitsa (d426ea32b4b02d40070c3aea6261cd6d42820d18242aa599ab1f6e4ae7b616e8): Error starting userland proxy: listen tcp 0.0.0.0:40708: bind: address already in use"}

	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:293) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:116) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43) ~[testcontainers-1.14.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.testcontainers.dockerclient.AuditLoggingDockerClient.lambda$wrappedCommand$14(AuditLoggingDockerClient.java:102) ~[testcontainers-1.14.3.jar:?]
	at com.sun.proxy.$Proxy45.exec(Unknown Source) ~[?:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:419) ~[testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325) ~[testcontainers-1.14.3.jar:?]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) [duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323) [testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311) [testcontainers-1.14.3.jar:?]
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.initMySql(MySqlCdcNetworkIntegrationTest.java:355) [test-classes/:?]
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringBinlogReading(MySqlCdcNetworkIntegrationTest.java:258) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114) [hazelcast-4.0.3-SNAPSHOT-tests.jar:4.0.3-SNAPSHOT]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106) [hazelcast-4.0.3-SNAPSHOT-tests.jar:4.0.3-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2020-09-20 13:40:34,883 [ERROR] [when_databaseShutdownDuringBinlogReading] [d.2]]: There are no stdout/stderr logs available for the failed container
2020-09-20 13:40:34,883 [ INFO] [when_databaseShutdownDuringBinlogReading] [d.2]]: Creating container for image: debezium/example-mysql:1.2
2020-09-20 13:40:35,414 [ INFO] [when_databaseShutdownDuringBinlogReading] [d.2]]: Starting container with ID: 36042f6571667c909788f0550aa03435a5214e6a6c71ad922cf0859ba5f1dc4f
2020-09-20 13:40:35,607 [ERROR] [when_databaseShutdownDuringBinlogReading] [d.2]]: Could not start container
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"driver failed programming external connectivity on endpoint infallible_elbakyan (ee951ee7d11957fb1fe03ca618104172637732b1e83e97617c9ed0fa774eb6f6): Error starting userland proxy: listen tcp 0.0.0.0:40708: bind: address already in use"}

	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:293) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:116) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[testcontainers-1.14.3.jar:?]
	at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43) ~[testcontainers-1.14.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.testcontainers.dockerclient.AuditLoggingDockerClient.lambda$wrappedCommand$14(AuditLoggingDockerClient.java:102) ~[testcontainers-1.14.3.jar:?]
	at com.sun.proxy.$Proxy45.exec(Unknown Source) ~[?:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:419) ~[testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325) ~[testcontainers-1.14.3.jar:?]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) [duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323) [testcontainers-1.14.3.jar:?]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311) [testcontainers-1.14.3.jar:?]
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.initMySql(MySqlCdcNetworkIntegrationTest.java:355) [test-classes/:?]
	at com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest.when_databaseShutdownDuringBinlogReading(MySqlCdcNetworkIntegrationTest.java:258) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114) [hazelcast-4.0.3-SNAPSHOT-tests.jar:4.0.3-SNAPSHOT]
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106) [hazelcast-4.0.3-SNAPSHOT-tests.jar:4.0.3-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
...
Hiccups measured while running test 'when_databaseShutdownDuringBinlogReading[fail](com.hazelcast.jet.cdc.mysql.MySqlCdcNetworkIntegrationTest):'
13:40:30, accumulated pauses: 51 ms, max pause: 20 ms, pauses over 1000 ms: 0
13:40:35, accumulated pauses: 14 ms, max pause: 6 ms, pauses over 1000 ms: 0
```

### PR DESCRIPTION
**Pull request by jbartok**
Issue is caused by some kind of cleanup problem, affecting the Ryuk resource reapers. This resource manager is not mandatory, tests already do manual container management, so will disable it. Hopefully the reduced complexity will get rid of the clean-up issues experienced.

Fixes #2534

### CODE REVIEW

**Comment by jbartok** [comment]
run-cdc-mysql-tests

**Comment by jbartok** [comment]
run-cdc-postgres-tests

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder-cdc-mysql-tests` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-cdc-mysql-tests/12/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-cdc-mysql-tests/12/jet-oss-pr-builder-cdc-mysql-tests-12.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (distro-assembly) on project hazelcast-jet-cdc-mysql: Failed to create assembly: Unable to resolve dependencies for assembly 'jar-with-dependencies': Failed to resolve dependencies for assembly: No versions are present in the repository for the artifact with a range [4.9,)
--------------------------
</details>
</pre>

**Comment by jbartok** [comment]
run-cdc-mysql-tests

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder-cdc-mysql-tests` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-cdc-mysql-tests/13/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-cdc-mysql-tests/13/jet-oss-pr-builder-cdc-mysql-tests-13.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</details>
</pre>

**Comment by olukas** [comment]
run-cdc-mysql-tests

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder-cdc-mysql-tests` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-cdc-mysql-tests/14/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-cdc-mysql-tests/14/jet-oss-pr-builder-cdc-mysql-tests-14.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>

</details>
</pre>

**Comment by olukas** [comment]
run-cdc-mysql-tests

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder-cdc-mysql-tests` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-cdc-mysql-tests/15/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-cdc-mysql-tests/15/jet-oss-pr-builder-cdc-mysql-tests-15.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (distro-assembly) on project hazelcast-jet-cdc-postgres: Failed to create assembly: Unable to resolve dependencies for assembly 'jar-with-dependencies': Failed to resolve dependencies for assembly: No versions are present in the repository for the artifact with a range [4.9,)
--------------------------
</details>
</pre>

**Comment by jbartok** [comment]
run-cdc-mysql-tests

**Comment by jbartok** [comment]
run-cdc-mysql-tests

**Comment by jbartok** [comment]
run-cdc-postgres-tests

**Comment by jbartok** [comment]
run-cdc-mysql-tests

**Comment by jbartok** [comment]
run-cdc-postgres-tests

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder-cdc-mysql-tests` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-cdc-mysql-tests/18/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-cdc-mysql-tests/18/jet-oss-pr-builder-cdc-mysql-tests-18.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (distro-assembly) on project hazelcast-jet-cdc-mysql: Failed to create assembly: Unable to resolve dependencies for assembly 'jar-with-dependencies': Failed to resolve dependencies for assembly: No versions are present in the repository for the artifact with a range [4.9,)
--------------------------
</details>
</pre>

**Comment by jbartok** [comment]
run-cdc-mysql-tests

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder-cdc-mysql-tests` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-cdc-mysql-tests/19/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-cdc-mysql-tests/19/jet-oss-pr-builder-cdc-mysql-tests-19.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (distro-assembly) on project hazelcast-jet-cdc-postgres: Failed to create assembly: Unable to resolve dependencies for assembly 'jar-with-dependencies': Failed to resolve dependencies for assembly: No versions are present in the repository for the artifact with a range [4.9,)
--------------------------
</details>
</pre>

**Comment by jbartok** [comment]
run-cdc-mysql-tests

File: extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java [hunk 1]
```diff
@@ -93,6 +99,12 @@
         });
     }
 
+    @Before
+    public void before() {
```
Comment (frant-hartm) [inline extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java:103]: Could you add a comment explaining this? I have no idea why it is needed.

File: extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java [hunk 2]
```diff
@@ -139,31 +151,34 @@ public void when_networkDisconnectDuringSnapshotting_then_jetSourceIsStuckUntilR
...
+                JetInstance jet = createJetMembers(2)[0];
+                Job job = jet.newJob(pipeline);
+                assertJobStatusEventually(job, RUNNING);
 
-            // and snapshotting is ongoing (we have no exact way of identifying
-            // the moment, but random sleep will catch it at least some of the time)
-            TimeUnit.MILLISECONDS.sleep(ThreadLocalRandom.current().nextInt(0, 500));
+                // and snapshotting is ongoing (we have no exact way of identifying
+                // the moment, but random sleep will catch it at least some of the time)
+                TimeUnit.MILLISECONDS.sleep(ThreadLocalRandom.current().nextInt(0, 500));
```
Comment (frant-hartm) [inline extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java:164]: Not related to this PR, but could it be made more deterministic by having a `CountDownLatch`, call `await` here and CountDownLatch#countDown in a first step of the pipeline (peek/map)?

**Review by frant-hartm — CHANGES_REQUESTED** [review]

File: extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java (hunk 2 above)
Comment (jbartok) [reply extensions/cdc-mysql/src/test/java/com/hazelcast/jet/cdc/mysql/MySqlCdcNetworkIntegrationTest.java:164]: In this test I'm trying to see what happens if the connection to the DB drops while snapshotting is going on. Snapshotting is a process with 9 stages. I'm interested to see what happens in all the stages, on connection drop. If I would make the test more deterministic (for example the way you suggest), then it would probably always trigger around the same stage, towards the end or after snapshotting. I don't want that. With such a random sleep there will eventually always be runs for all possible scenarios. Yes, it's not deterministic, will be hard to debug, but if there is a problem we will likely find out about it. Eventually. This was my thinking.

**Review by frant-hartm — APPROVED** [review]

**Review by olukas — CHANGES_REQUESTED** [review]
We should not merge this until we will resolve intermittent failure in maven:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (distro-assembly) on project hazelcast-jet-cdc-postgres: Failed to create assembly: Unable to resolve dependencies for assembly 'jar-with-dependencies': Failed to resolve dependencies for assembly: No versions are present in the repository for the artifact with a range [4.9,)
[ERROR]   junit:junit-dep:jar:null
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   snapshot-repository (https://oss.sonatype.org/content/repositories/snapshots, releases=false, snapshots=true),
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] Path to dependency: 
[ERROR] 	1) com.hazelcast.jet:hazelcast-jet-cdc-postgres:jar:4.3-SNAPSHOT
[ERROR] 	2) com.github.stefanbirkner:system-rules:jar:1.19.0
[ERROR] -> [Help 1]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (distro-assembly) on project hazelcast-jet-cdc-mysql: Failed to create assembly: Unable to resolve dependencies for assembly 'jar-with-dependencies': Failed to resolve dependencies for assembly: No versions are present in the repository for the artifact with a range [4.9,)
[ERROR]   junit:junit-dep:jar:null
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   snapshot-repository (https://oss.sonatype.org/content/repositories/snapshots, releases=false, snapshots=true),
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] Path to dependency: 
[ERROR] 	1) com.hazelcast.jet:hazelcast-jet-cdc-mysql:jar:4.3-SNAPSHOT
[ERROR] 	2) com.github.stefanbirkner:system-rules:jar:1.19.0
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hazelcast-jet-cdc-postgres
```

I hit it even locally, this is not related to jenkins. I'm afraid that merging it will cause a troubles in jenkins tests and PR builder jobs.

`junit-dep` was integrated to `junit` from version `4.12` (which is used by our testsuite). When I excluded `junit-dep` from `system-rules` dependency then I have not met this issue and test passed (see http://jenkins.hazelcast.com/view/Jet%20-%20Misc/job/jet-custom-oss-nightly/5/). Can you try to use it in this PR:
```
<dependency>
    <groupId>com.github.stefanbirkner</groupId>
    <artifactId>system-rules</artifactId>
    <version>1.19.0</version>
    <scope>test</scope>
    <exclusions>
        <exclusion>
            <groupId>junit</groupId>
            <artifactId>junit-dep</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Review by olukas — APPROVED** [review]
