### PR TITLE
Use job-level serializer to get partition id

### LINKED ISSUE #2188: No suitable serializer when job-level serialization should happen
When job-level serializer is registered and job is distributed across nodes and serialization should really happen then `com.hazelcast.nio.serialization.HazelcastSerializationException` is thrown. 

This does not happen if:
- given serializer is registered globally
- pipeline is running only on single node

Thrown exception (for mentioned below reproducer):
```
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.mycompany.simple.jet.app.Value'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:115)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:173)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:149)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:134)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:122)
	at com.hazelcast.spi.impl.NodeEngineImpl.toData(NodeEngineImpl.java:334)
	at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.getPartitionId(InternalPartitionServiceImpl.java:950)
	at com.hazelcast.jet.core.Partitioner$Default.getPartition(Partitioner.java:122)
	at com.hazelcast.jet.core.Edge$KeyPartitioner.getPartition(Edge.java:603)
	at com.hazelcast.jet.impl.execution.OutboundCollector$Partitioned.offer(OutboundCollector.java:193)
	at com.hazelcast.jet.impl.execution.OutboxImpl.doOffer(OutboxImpl.java:251)
	at com.hazelcast.jet.impl.execution.OutboxImpl.offerInternal(OutboxImpl.java:139)
	at com.hazelcast.jet.impl.execution.OutboxImpl.offer(OutboxImpl.java:94)
	at com.hazelcast.jet.core.AbstractProcessor.tryEmit(AbstractProcessor.java:309)
	at com.hazelcast.jet.core.AbstractProcessor.emitFromTraverser(AbstractProcessor.java:408)
	at com.hazelcast.jet.core.AbstractProcessor.emitFromTraverser(AbstractProcessor.java:421)
	at com.hazelcast.jet.impl.processor.GroupP.complete(GroupP.java:88)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:465)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:365)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:240)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:366)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:346)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable serializer for class com.mycompany.simple.jet.app.Value
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.serializerFor(AbstractSerializationService.java:507)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:162)
	... 22 more
```

**Steps to reproduce:**
Run following code:
```
Pipeline p = Pipeline.create();
p.readFrom(Sources.<String>list("text"))
        .flatMap(line -> traverseArray(line.toLowerCase().split("\\W+")))
        .map(t -> new Value(t))
        .filter(word -> !word.getValue().isEmpty())
        // if you comment out groupingKey+aggregate stage then it works (it will run on single node)
        .groupingKey(wholeItem())
        .aggregate(counting())
        .writeTo(Sinks.list("list"));


JetConfig config = new JetConfig();
// it works if you register serializer globally
// config.getHazelcastConfig().getSerializationConfig()
//         .addSerializerConfig(new SerializerConfig().setTypeClass(Value.class).setClass(ValueSerializer.class));
JetInstance jet = Jet.newJetInstance(config);
JetInstance jet2 = Jet.newJetInstance(config);

List<String> text = jet.getList("text");
text.add("hello world hello hello world");

JobConfig jc = new JobConfig();
jc.addClass(Main.class, Value.class, ValueSerializer.class);
jc.registerSerializer(Value.class, ValueSerializer.class);
jet.newJob(p, jc).join();
```
where `Value` class is:
```
public class Value {

    private String value;

    public Value() {
    }

    public Value(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Value value1 = (Value) o;
        return value == value1.value;
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }
}
```
and `ValueSerializer` is:
```
public class ValueSerializer implements StreamSerializer<Value> {

    @Override
    public int getTypeId() {
        return 1;
    }

    @Override
    public void write(ObjectDataOutput output, Value value) throws IOException {
        output.writeUTF(value.getValue());
    }

    @Override
    public Value read(ObjectDataInput input) throws IOException {
        return new Value(input.readUTF());
    }
}
```

**What you can also try with reproducer:**
- comment out groupingKey+aggregate stage from pipeline - it will not fail (job is not distributed across cluster)
- uncomment serialization config for members - it will not fail because it will register serializer globally
- you can also comment out line `jc.registerSerializer(Value.class, ValueSerializer.class);` to see that it checks that serializer is added but it is not able to actually use it

### PR DESCRIPTION
**Pull request by gierlachg**
Added support for getting partition id with job-level serializer.

Checklist
- [x] Tags Set
- [x] Milestone Set

Fixes #2188

### CODE REVIEW

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java [hunk 1]
```diff
@@ -344,7 +344,8 @@ private void initDag() {
                 .flatMap(List::stream)
                 .map(EdgeDef::partitioner)
                 .filter(Objects::nonNull)
-                .forEach(p -> p.init(partitionService::getPartitionId));
+                .forEach(partitioner ->
+                        partitioner.init(object -> partitionService.getPartitionId(serializationService.toData(object))));
```
Comment (cangencer) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java:348]: very minor but I find it more readable if the closing `)` is on the next line here.

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java [hunk 2]
```diff
@@ -148,7 +148,7 @@ public void initialize(NodeEngine nodeEngine,
         this.nodeEngine = (NodeEngineImpl) nodeEngine;
         this.executionId = executionId;
         initProcSuppliers(jobId, executionId, tempDirectories, serializationService);
-        initDag();
+        initDag(serializationService);
```
Comment (cangencer) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java:151]: this should be called `jobSerializationService`

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/2686/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/2686/jet-oss-pr-builder-2686.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:checkstyle (default) on project hazelcast-jet-core: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.29 with /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder_2/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder_2/hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java:371: Line is longer than 123 characters (found 124). [LineLength]
--------------------------
</details>
</pre>
