### PR TITLE
Improve constantKey perf, fix global aggregation

### LINKED ISSUE #1240: Don't use same constant key for all global aggregations
Currently all global aggregations use the same key [(here)](https://github.com/hazelcast/hazelcast-jet/blob/5dd0ac78d0c2caceb3102640588e68bff537db64/hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/DistributedFunctions.java#L31). This causes that all aggregations run on the same member and snapshots are stored in the same partition.  We should use constant, but randomly generated key for each aggregation.

### PR DESCRIPTION
**Pull request by viliam-durina**
Each invocation of constantKey() will return a different function
instance, that constantly returns a random key.

Fixes #1240

### CODE REVIEW

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/PipelineImpl.java [hunk 1]
```diff
@@ -158,6 +154,16 @@ public String toDotString() {
 
     void register(Transform stage, List<Transform> downstream) {
         List<Transform> prev = adjacencyMap.put(stage, downstream);
-        assert prev == null : "Double registering of a Stage with this Pipeline: " + stage;
+        assert prev == null : "Double registration of a Stage with this Pipeline: " + stage;
+    }
+
+    void makeNamesUnique() {
+        Set<String> usedNames = new HashSet<>();
+        for (Transform transform : adjacencyMap.keySet()) {
```
Comment (cangencer) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/PipelineImpl.java]: is this done in topological way? so we don't end up with stages like map-3 -> map-2 -> map

Comment (viliam-durina) [reply hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/PipelineImpl.java]: Yes, pipeline transforms are always added in topological order. You can't add sink before the source. It's also checked [here](https://github.com/hazelcast/hazelcast-jet/pull/1242/files#diff-f1c767808988b2fb6d4adb9a4971023bR107) before creating the DAG.

Comment (mtopolnik) [reply hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/PipelineImpl.java]: Once we start modifying the transform DAG, it will disturb the assumed ordering.

Comment (viliam-durina) [reply hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/PipelineImpl.java]: We don't do it now. That's why there's the check in `createDag`: if we ever unintentionally break the order, it will fail.

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/DistributedFunctions.java [hunk 2]
```diff
@@ -63,12 +60,14 @@ private DistributedFunctions() {
...
+     * Returns a function that always evaluates to the given {@code key}. This
+     * is useful as a key extractor in group-by operations where no
+     * classification by key is desired; in other words, a global group is
+     * used. Choose a random {@code key} so that each global group is handled
+     * by a random member.
      */
     @Nonnull
-    public static <T> DistributedFunction<T, String> constantKey() {
-        return t -> CONSTANT_KEY;
+    public static <T, K> DistributedFunction<T, K> constantKey(K key) {
```
Comment (cangencer) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/DistributedFunctions.java]: does this need to be part of public API? I think it would be better to move it to `ConstantFunction`

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StreamStageImpl.java [hunk 3]
```diff
@@ -131,7 +131,7 @@ public StreamStageImpl(
 
     @Nonnull @Override
     public <R> StreamStage<R> rollingAggregate(@Nonnull AggregateOperation1<? super T, ?, ? extends R> aggrOp) {
-        return groupingKey(constantKey()).rollingAggregate(aggrOp, (k, v) -> v);
+        return groupingKey(constantKey(name().hashCode())).rollingAggregate(aggrOp, (k, v) -> v);
```
Comment (cangencer) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StreamStageImpl.java]: is it a good idea to use `name`? it's always generated to the same value if not explicitly set (i.e. rolling-aggregate)

Comment (viliam-durina) [reply hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/StreamStageImpl.java]: Hmm, true, in this place it's not unique, it's made unique later when calling `createDag`.

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/DistributedFunctions.java (hunk 2 above)
Comment (viliam-durina) [reply hazelcast-jet-core/src/main/java/com/hazelcast/jet/function/DistributedFunctions.java]: Yes, it doesn't. Pipeline API uses it internally and it's not needed for core api - the user can use `allToOne` and appropriate key extractor in the downstream vertex.

**Comment by cangencer** [comment]
verify

**Comment by viliam-durina** [comment]
Breaking changes in the PR: 
- `DistributedFunction.constantKey()` is removed
- `Edge.allToOne()` has one parameter added: the constant key. It used to 
generate random key, which broke job upgradability and also broke joins which
the user intuitively guessed will go to the same processor: all-to-one didn't mean
all-to-the-same-one.
