### PR TITLE
Attempt to fix Observable tests

### LINKED ISSUE #2026: com.hazelcast.jet.core.ObservableResultsTest.getObservables[1: mode=client]
_master_ (commit f7cf5b2ed0761c8010791beec1fdf49699606f66)

Failed on IBM JDK 8: http://jenkins.hazelcast.com/job/jet-oss-master-ibm-jdk8/165/testReport/com.hazelcast.jet.core/ObservableResultsTest/getObservables_1__mode_client_/

Stacktrace:
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.jet.core.ObservableResultsTest.getObservables(ObservableResultsTest.java:564)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:818)
```

Standard output:
```
Hiccups measured while running test 'getObservables[1: mode=client](com.hazelcast.jet.core.ObservableResultsTest):'
02:00:15, accumulated pauses: 109 ms, max pause: 46 ms, pauses over 1000 ms: 0
```

### PR DESCRIPTION
**Pull request by jbartok**
Attempt to fix some flaky tests for Observables. Even though can't reproduce the failures it seems to be caused by not cleaning up properly after tests.

Checklist
- [x] Tags Set
- [x] Milestone Set

Fixes #2026

### CODE REVIEW

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/TestInClusterSupport.java [hunk 1]
```diff
@@ -51,7 +51,7 @@
     protected static final String JOURNALED_CACHE_PREFIX = "journaledCache.";
     protected static final int MEMBER_COUNT = 2;
 
-    protected static JetTestInstanceFactory factory = new JetTestInstanceFactory();
+    protected static JetTestInstanceFactory FACTORY = new JetTestInstanceFactory();
```
Comment (cangencer) [inline hazelcast-jet-core/src/test/java/com/hazelcast/jet/TestInClusterSupport.java:54]: caps is only used for static final variables (i.e. constants?)

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ObservableResultsTest.java [hunk 2]
```diff
@@ -63,20 +63,19 @@
...
         testObserver = new TestObserver();
-        testObservable = getObservable(observableName);
+        testObservable = jet().getObservable(observableName);
         registrationId = testObservable.addObserver(testObserver);
     }
 
     @After
-    public void after() {
-        usedObservables.forEach(Observable::destroy);
+    public void after() throws Exception {
```
Comment (cangencer) [inline hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ObservableResultsTest.java:76]: method should have `@Override` if it's overriding, or you can just use another method name

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/TestInClusterSupport.java (hunk 1 above)
Comment (jbartok) [reply hazelcast-jet-core/src/test/java/com/hazelcast/jet/TestInClusterSupport.java:54]: Ok, will revert. Truth to be told I've not come across that many non-final static fields in the past and I've never stopped to consciously make this distinction.

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ObservableResultsTest.java [hunk 3]
```diff
@@ -553,15 +553,19 @@ public void unnamedObservable() {
...
+        Observable<Object> c = jet().newObservable();
+
+        a.addObserver(Observer.of(ConsumerEx.noop()));
+        c.addObserver(Observer.of(ConsumerEx.noop()));
 
         //then
         Set<String> activeObservables = jet().getObservables().stream().map(Observable::name).collect(Collectors.toSet());
-        assertTrue(activeObservables.containsAll(Arrays.asList("a", "c")));
+        assertTrue(activeObservables.containsAll(Arrays.asList(a.name(), c.name())));
+        assertFalse(activeObservables.contains(b.name()));
```
Comment (viliam-durina) [inline hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ObservableResultsTest.java:568]: We can do this:
```suggestion
        assertEquals(new HashSet<>(Arrays.asList(a.name(), c.name())), activeObservables);
```
This way we'll see in the exception message what's the difference.

Comment (jbartok) [reply hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/ObservableResultsTest.java:568]: Not really, because they are not equal (there are other, extra names in there too). Plus it wouldn't really help. All it would tell us is if `a` or `c` is missing, but that wouldn't help. Anyways, I'll investigate further if it happens again.
