### PR TITLE
Set job's classloader on each tasklet call

### LINKED ISSUE #387: addClass() doesn't appear to have an effect
I did the following:

1. Download Jet 0.3.1 from the website
2. bin/start.sh
3. execute the client code:

```java
public class Main {
    public static void main(String[] args) throws Exception {
        try {
            ClientConfig conf = new ClientConfig();
            conf.setCredentials(new UsernamePasswordCredentials("jet", "jet-pass"));
            JetInstance jet = Jet.newJetClient(conf);
            IStreamMap<Object, Object> events = jet.getMap("events");
            IStreamMap<Object, Object> newevents = jet.getMap("newevents");
            events.clear();
            newevents.clear();
            for (int i = 0; i < 1000; i++) {
                events.put(i, new Event(System.nanoTime(), "key" + i, "value"));
            }
            JobConfig jconf = new JobConfig().addClass(Event.class);
            jet.newJob(buildDag(), jconf).execute().get();
            System.out.println("Output map size: " + newevents.size());
        } finally {
            Jet.shutdownAll();
        }
    }

    private static DAG buildDag() {
        DAG dag = new DAG();
        Vertex source = dag.newVertex("source", readMap("events"));
        Vertex sink = dag.newVertex("sink", writeMap("newevents"));
        dag.edge(between(source, sink));
        return dag;
    }
}

public class Event implements Serializable {
    long timestamp;
    String key;
    String value;

    Event(long timestamp, String key, String value) {
        this.timestamp = timestamp;
        this.key = key;
        this.value = value;
    }
}
```

The outcome is:

```
Job execution failed with exception
Apr 17, 2017 6:14:08 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [dev] [0.3.1] [3.8] HazelcastClient 3.8 (20170217 - d7998b4) is CLIENT_CONNECTED
java.util.concurrent.ExecutionException: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{vertex=sink, processor=com.hazelcast.jet.impl.connector.WriteIMapP@79e48f8e}: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: test.Event
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:87)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:31)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.jet.impl.JetClientInstanceImpl$ExecutionFuture.get(JetClientInstanceImpl.java:177)
	at com.hazelcast.jet.impl.JetClientInstanceImpl$ExecutionFuture.get(JetClientInstanceImpl.java:132)
	at test.Main.main(Main.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)Job execution failed with exception

	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{vertex=sink, processor=com.hazelcast.jet.impl.connector.WriteIMapP@79e48f8e}: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: test.Event
	at com.hazelcast.jet.impl.execution.ExecutionService$BlockingWorker.run(ExecutionService.java:165)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:74)
	... 10 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: test.Event
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:224)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:184)
	at com.hazelcast.query.impl.CachedQueryEntry.getValue(CachedQueryEntry.java:70)
	at com.hazelcast.map.impl.proxy.MapProxySupport.putAllInternal(MapProxySupport.java:796)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.putAll(MapProxyImpl.java:377)
	at com.hazelcast.jet.impl.connector.WriteIMapP.flush(WriteIMapP.java:68)
	at com.hazelcast.jet.impl.connector.WriteIMapP.process(WriteIMapP.java:52)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.tryProcessInbox(ProcessorTasklet.java:148)
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:99)
	at com.hazelcast.jet.impl.execution.ExecutionService$BlockingWorker.run(ExecutionService.java:155)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: test.Event
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:146)
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:120)
	at com.hazelcast.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:522)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:219)
	... 15 more
Output map size: 0
```

### PR DESCRIPTION
**Pull request by mtopolnik**
A Jet job would fail when trying to deserialize a user's custom class fetched from a Hazelcast IMap. The same failure would arise in deserialization that follows a distributed edge.

The solution is to always set the job's custom classloader as the thread's context classloader before calling into a tasklet.

Fixes #387

### CODE REVIEW

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionService.java [hunk 1]
```diff
@@ -186,6 +195,7 @@ public void run() {
                         continue;
                     }
                     try {
+                        thread.setContextClassLoader(t.jobClassLoader);
```
Comment (cangencer) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionService.java]: TCCL should be swapped out when Tasklet is dismissed, to prevent hanging on to the reference.

Comment (mtopolnik) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/execution/ExecutionService.java]: Swapping out when idle.
