### PR TITLE
Fix @Nullable name in BatchStage

### LINKED ISSUE #1675: Inconsistent @Nonnull and @Nullable annotations
`BatchStage.setName()` has `@Nullable` parameter, but some subclasses have it `@Nonnull`.

### PR DESCRIPTION
**Pull request by cangencer**
Fixes #1675

### CODE REVIEW

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/AbstractTransform.java [hunk 1]
```diff
@@ -50,6 +51,7 @@ protected AbstractTransform(String name, @Nonnull Transform upstream) {
 
     @Override
     public void setName(@Nonnull String name) {
+        Objects.requireNonNull(name, " name");
```
Comment (viliam-durina) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/transform/AbstractTransform.java]: You can do 
```
this.name = requireNonNull(name, "name");
```
There's also extra space in the string

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/AbstractStage.java [hunk 2]
```diff
@@ -21,9 +21,11 @@
 import com.hazelcast.jet.pipeline.Pipeline;
 import com.hazelcast.jet.pipeline.SinkStage;
 import com.hazelcast.jet.pipeline.Stage;
+import jdk.internal.jline.internal.Preconditions;
```
Comment (viliam-durina) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/AbstractStage.java]: Import from `jdk.internal`?

Comment (cangencer) [reply hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/pipeline/AbstractStage.java]: This was leftover from when I added the check to AbstractStage, fixed now.
