### PR TITLE
Check if python3 is available before initializing python service context

### LINKED ISSUE #2615: mapUsingPython: explicitly check availability of Python, produce a user-friendly message
When running in a Docker image that doesn't include Python, `PythonTransforms.mapUsingPythonBatch` unsurprisingly fails. 

However, the failure cause is not shown, which makes it difficult for the user to diagnose, you only get

```
Caused by: java.lang.Exception: Initialization script finished with non-zero exit code: 127
```

So this is user error ultimately, but little diagnostic support.

Steps to recreate, create a Docker image using `FROM library/openjdk:11-jre-slim` that starts a Jet server, and run that Jet server. Then inject the job from a Jet client.

I get
```
11:53:53.940 [hz.competent_lalande.cached.thread-3] WARN  com.hazelcast.jet.impl.processor.ProcessorSupplierWithService.mapUsingPythonBatch#ProcessorSupplier - PythonService context creation failed,  will retry
 com.hazelcast.jet.JetException: PythonService initialization failed: java.lang.Exception: Initialization script finished with non-zero exit code: 127
	at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:110) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	at com.hazelcast.jet.python.PythonService.createContextWithRetry(PythonService.java:111) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	at com.hazelcast.jet.python.PythonService.lambda$factory$9a0f8f23$1(PythonService.java:91) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:47) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.processor.ProcessorSupplierWithService.init(ProcessorSupplierWithService.java:55) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initProcSuppliers(ExecutionPlan.java:327) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initialize(ExecutionPlan.java:158) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.execution.ExecutionContext.initialize(ExecutionContext.java:138) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobExecutionService.lambda$initExecution$808bb183$1(JobExecutionService.java:240) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:30) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:446) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobExecutionService.initExecution(JobExecutionService.java:240) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.operation.InitExecutionOperation.run(InitExecutionOperation.java:73) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:227) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:596) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:581) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:237) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:261) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:245) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterJobContext.lambda$tryStartJob$2(MasterJobContext.java:227) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1024) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1033) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1023) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterJobContext.tryStartJob(MasterJobContext.java:189) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.tryStartJob(JobCoordinationService.java:933) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:258) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1024) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47(JobCoordinationService.java:1045) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
Caused by: java.lang.Exception: Initialization script finished with non-zero exit code: 127
	at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:101) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	... 40 more
11:53:54.968 [hz.competent_lalande.cached.thread-3] WARN  com.hazelcast.jet.impl.processor.ProcessorSupplierWithService.mapUsingPythonBatch#ProcessorSupplier - PythonService context creation failed,  will retry
 com.hazelcast.jet.JetException: PythonService initialization failed: java.lang.Exception: Initialization script finished with non-zero exit code: 127
	at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:110) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	at com.hazelcast.jet.python.PythonService.createContextWithRetry(PythonService.java:111) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	at com.hazelcast.jet.python.PythonService.lambda$factory$9a0f8f23$1(PythonService.java:91) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:47) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.processor.ProcessorSupplierWithService.init(ProcessorSupplierWithService.java:55) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initProcSuppliers(ExecutionPlan.java:327) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initialize(ExecutionPlan.java:158) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.execution.ExecutionContext.initialize(ExecutionContext.java:138) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobExecutionService.lambda$initExecution$808bb183$1(JobExecutionService.java:240) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:30) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:446) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobExecutionService.initExecution(JobExecutionService.java:240) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.operation.InitExecutionOperation.run(InitExecutionOperation.java:73) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:227) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:596) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:581) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:237) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:261) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:245) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterJobContext.lambda$tryStartJob$2(MasterJobContext.java:227) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1024) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1033) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1023) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterJobContext.tryStartJob(MasterJobContext.java:189) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.tryStartJob(JobCoordinationService.java:933) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:258) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1024) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47(JobCoordinationService.java:1045) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
Caused by: java.lang.Exception: Initialization script finished with non-zero exit code: 127
	at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:101) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	... 40 more
11:53:55.978 [hz.competent_lalande.cached.thread-3] WARN  com.hazelcast.jet.impl.processor.ProcessorSupplierWithService.mapUsingPythonBatch#ProcessorSupplier - PythonService context creation failed,  giving up
 com.hazelcast.jet.JetException: PythonService initialization failed: java.lang.Exception: Initialization script finished with non-zero exit code: 127
	at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:110) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	at com.hazelcast.jet.python.PythonService.createContextWithRetry(PythonService.java:111) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	at com.hazelcast.jet.python.PythonService.lambda$factory$9a0f8f23$1(PythonService.java:91) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:47) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.processor.ProcessorSupplierWithService.init(ProcessorSupplierWithService.java:55) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initProcSuppliers(ExecutionPlan.java:327) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initialize(ExecutionPlan.java:158) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.execution.ExecutionContext.initialize(ExecutionContext.java:138) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobExecutionService.lambda$initExecution$808bb183$1(JobExecutionService.java:240) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:30) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:446) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobExecutionService.initExecution(JobExecutionService.java:240) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.operation.InitExecutionOperation.run(InitExecutionOperation.java:73) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:227) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:596) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:581) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:237) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:261) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:245) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterJobContext.lambda$tryStartJob$2(MasterJobContext.java:227) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1024) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1033) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1023) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterJobContext.tryStartJob(MasterJobContext.java:189) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.tryStartJob(JobCoordinationService.java:933) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:258) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1024) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47(JobCoordinationService.java:1045) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
Caused by: java.lang.Exception: Initialization script finished with non-zero exit code: 127
	at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:101) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	... 40 more
11:53:56.981 [hz.competent_lalande.cached.thread-3] ERROR com.hazelcast.jet.impl.operation.InitExecutionOperation - PythonService initialization failed: java.lang.Exception: Initialization script finished with non-zero exit code: 127
 com.hazelcast.jet.JetException: PythonService initialization failed: java.lang.Exception: Initialization script finished with non-zero exit code: 127
	at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:110) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	at com.hazelcast.jet.python.PythonService.createContextWithRetry(PythonService.java:111) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	at com.hazelcast.jet.python.PythonService.lambda$factory$9a0f8f23$1(PythonService.java:91) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:47) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.processor.ProcessorSupplierWithService.init(ProcessorSupplierWithService.java:55) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initProcSuppliers(ExecutionPlan.java:327) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initialize(ExecutionPlan.java:158) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.execution.ExecutionContext.initialize(ExecutionContext.java:138) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobExecutionService.lambda$initExecution$808bb183$1(JobExecutionService.java:240) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:30) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:446) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobExecutionService.initExecution(JobExecutionService.java:240) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.operation.InitExecutionOperation.run(InitExecutionOperation.java:73) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:227) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:596) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:581) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:237) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:261) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:245) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterJobContext.lambda$tryStartJob$2(MasterJobContext.java:227) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1024) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1033) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1023) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterJobContext.tryStartJob(MasterJobContext.java:189) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.tryStartJob(JobCoordinationService.java:933) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:258) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1024) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47(JobCoordinationService.java:1045) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
Caused by: java.lang.Exception: Initialization script finished with non-zero exit code: 127
	at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:101) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	... 40 more
11:53:57.000 [hz.competent_lalande.cached.thread-3] ERROR com.hazelcast.jet.impl.MasterJobContext - Execution of job 'MLChurnDetector@2020-10-24T11:53:52', execution 052a-dc2a-e3c0-0001 failed
	Start time: 2020-10-24T11:53:53.785
	Duration: 3,214 ms
	To see additional job metrics enable JobConfig.storeMetricsAfterJobCompletion
 com.hazelcast.jet.JetException: PythonService initialization failed: java.lang.Exception: Initialization script finished with non-zero exit code: 127
	at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:110) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	at com.hazelcast.jet.python.PythonService.createContextWithRetry(PythonService.java:111) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	at com.hazelcast.jet.python.PythonService.lambda$factory$9a0f8f23$1(PythonService.java:91) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	at com.hazelcast.function.FunctionEx.apply(FunctionEx.java:47) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.processor.ProcessorSupplierWithService.init(ProcessorSupplierWithService.java:55) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initProcSuppliers(ExecutionPlan.java:327) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.execution.init.ExecutionPlan.initialize(ExecutionPlan.java:158) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.execution.ExecutionContext.initialize(ExecutionContext.java:138) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobExecutionService.lambda$initExecution$808bb183$1(JobExecutionService.java:240) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:30) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:446) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobExecutionService.initExecution(JobExecutionService.java:240) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.operation.InitExecutionOperation.run(InitExecutionOperation.java:73) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:227) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:216) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:406) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:433) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:596) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:581) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:237) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:261) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:245) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterJobContext.lambda$tryStartJob$2(MasterJobContext.java:227) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1024) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1033) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.submitToCoordinatorThread(JobCoordinationService.java:1023) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.MasterJobContext.tryStartJob(MasterJobContext.java:189) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.tryStartJob(JobCoordinationService.java:933) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitJob$1(JobCoordinationService.java:258) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$46(JobCoordinationService.java:1024) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$47(JobCoordinationService.java:1045) ~[hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) [hazelcast-jet-enterprise-4.4-SNAPSHOT.jar!/:?]
Caused by: java.lang.Exception: Initialization script finished with non-zero exit code: 127
	at com.hazelcast.jet.python.PythonServiceContext.<init>(PythonServiceContext.java:101) ~[hazelcast-jet-python-4.4-SNAPSHOT.jar!/:4.4-SNAPSHOT]
	... 40 more
```

Occurs at least on 4.3 and 4.4-SNAPSHOT from 23/10/2020

### PR DESCRIPTION
**Pull request by gurbuzali**
Fixes #2615

Checklist:
- [x] Labels and Milestone set
- [ ] Added a line in `hazelcast-jet-distribution/src/root/release_notes.txt` (for any non-trivial fix/enhancement/feature)
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc
- [ ] Updated `examples/README.md` (when adding a new code sample)

### CODE REVIEW

File: extensions/python/src/main/java/com/hazelcast/jet/python/PythonServiceContext.java [hunk 1]
```diff
@@ -108,6 +109,14 @@
         }
     }
 
+    private void checkIfPythonIsAvailable() {
+        try {
+            new ProcessBuilder("python3", "--version").start().waitFor();
```
Comment (frant-hartm) [inline extensions/python/src/main/java/com/hazelcast/jet/python/PythonServiceContext.java:114]: Is there a minimal python3 version we require?

Also, this will pass if `python3 --version` runs, but returns exit code other than 0. Maybe it would be better to log the output of the command, exit code. Possibly parse the version & check.

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3662/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3662/jet-oss-pr-builder-3662.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:4.1.3:check (default) on project hazelcast-jet-python: failed with 1 bugs and 0 errors -> [Help 1]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3663/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3663/jet-oss-pr-builder-3663.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:checkstyle (default) on project hazelcast-jet-python: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.29 with /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder/extensions/python/src/main/java/com/hazelcast/jet/python/PythonServiceContext.java:32:8: Unused import - java.nio.charset.StandardCharsets. [UnusedImports]
--------------------------
</details>
</pre>

**Review by frant-hartm — APPROVED** [review]

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3664/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3664/jet-oss-pr-builder-3664.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   HazelcastConnector_RestartTest.when_iListWrittenAndMemberShutdown_then_jobRestarts:101 ? WrongTarget
[INFO] 
[ERROR] Tests run: 2280, Failures: 0, Errors: 1, Skipped: 10
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by gurbuzali** [comment]
verify
