### PR TITLE
Handle non-serializable exceptions in AsyncOperation

### LINKED ISSUE #1995: Job did not finish on cluster with more than 2 members if Python code failed
In case when python code fails in pipeline then job did not finish on cluster with 2 and more members. It works on single node cluster. 

Job is restarted every ~2minutes and 13seconds and following Exception can be seen in server log:
```
ERROR [c.h.j.i.o.StartExecutionOperation] [hz.loving_sutherland.jet.cooperative.thread-2] - [10.212.134.151]:5702 [jet] [4.0-SNAPSHOT] Exception during callback
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.spi.impl.operationservice.impl.responses.ErrorResponse'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:115)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:157)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:133)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:124)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.send(OutboundResponseHandler.java:114)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.sendResponse(OutboundResponseHandler.java:94)
	at com.hazelcast.spi.impl.operationservice.Operation.sendResponse(Operation.java:470)
	at com.hazelcast.jet.impl.operation.AsyncOperation.doSendResponse(AsyncOperation.java:76)
	at com.hazelcast.jet.impl.operation.AsyncOperation.lambda$run$0(AsyncOperation.java:56)
	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:180)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:59)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:458)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:392)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:378)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:346)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.jet.JetException'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:115)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:253)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:378)
	at com.hazelcast.spi.impl.operationservice.impl.responses.ErrorResponse.writeData(ErrorResponse.java:49)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:244)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:154)
	... 19 more
Caused by: java.io.NotSerializableException: io.grpc.Status
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
	at java.lang.Throwable.writeObject(Throwable.java:985)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
	at java.lang.Throwable.writeObject(Throwable.java:985)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:441)
	at java.lang.Throwable.writeObject(Throwable.java:985)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1140)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.write(JavaDefaultSerializers.java:115)
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.write(JavaDefaultSerializers.java:108)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:251)
	... 25 more
``` 

How to reproduce:
Use following python script named `failing.py`:
```
def handle(input_list):
    assert 1 == 2
    return ['echo-%s' % i for i in input_list]
```
Use follwing pipeline:
```
        PythonServiceConfig cfg = new PythonServiceConfig()
                .setBaseDir(PATH_TO_BASE_DIR)
                .setHandlerModule("failing")
                .setHandlerFunction("handle");
        Pipeline p = Pipeline.create();
        p.readFrom(TestSources.items("1"))
                .apply(mapUsingPythonBatch(cfg)).setLocalParallelism(2)
                .writeTo(Sinks.logger());
        jet.newJob(p).join();
```

### PR DESCRIPTION
**Pull request by cangencer**
Sometimes the processors may fail with a non-serializable exception.
Convert the exception to a String and fail with a generic exception in
this case.

Checklist
- [x] Tags Set
- [x] Milestone Set

Links to issues fixed (if any):

Fixes #1995

### CODE REVIEW

**Comment by olukas** [comment]
I observed issue https://github.com/hazelcast/hazelcast-jet/issues/1995 even with this PR - however it started to be intermittent - it happened in ~50% of attempts.

**Comment by cangencer** [comment]
It maybe because of which node it fails on and perhaps it fails on CompleteExecutionOperation as well.

**Comment by cangencer** [comment]
sending of CompleteExecutionOperation is still not handled in this case, but I added explicit handled for the gRPC exceptions which are not serializable.

File: extensions/python/src/test/java/com/hazelcast/jet/python/PythonServiceTest.java [hunk 1]
```diff
@@ -49,7 +49,12 @@
     private static final int ITEM_COUNT = 10_000;
     private static final String ECHO_HANDLER_FUNCTION =
             "def handle(input_list):\n" +
-            "    return ['echo-%s' % i for i in input_list]\n";
+ "    return ['echo-%s' % i for i in input_list]\n";
```
Comment (viliam-durina) [inline extensions/python/src/test/java/com/hazelcast/jet/python/PythonServiceTest.java]: Bad indentation

File: extensions/python/src/main/java/com/hazelcast/jet/python/PythonService.java [hunk 2]
```diff
@@ -128,6 +131,11 @@ public void onNext(OutputMessage outputItem) {
         @Override
         public void onError(Throwable e) {
             try {
+                if (e instanceof StatusException || e instanceof StatusRuntimeException) {
+                    // not seriazliable exceptions
```
Comment (viliam-durina) [inline extensions/python/src/main/java/com/hazelcast/jet/python/PythonService.java]: serializable

File: hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/AsyncOperation.java [hunk 3]
```diff
@@ -73,7 +76,17 @@ private void doSendResponse(Object value) {
             final JetService service = getService();
             service.getLiveOperationRegistry().deregister(this);
         } finally {
-            sendResponse(value);
+            try {
+                sendResponse(value);
+            } catch (Exception e) {
+                Throwable ex = peel(e);
+                if (value instanceof Throwable && ex instanceof HazelcastSerializationException) {
+                    // we got a non-serializable exception here
```
Comment (viliam-durina) [inline hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/operation/AsyncOperation.java]: I would expand this comment, something like:
> Sometimes exceptions are not serializable. For example https://github.com/hazelcast/hazelcast-jet/issues/1995. When sending exception as a response and the serialization fails, the response will not be sent and the operation will hang. If it happened, replace it with another exception that can be serialized.

File: extensions/python/src/test/java/com/hazelcast/jet/python/PythonServiceTest.java [hunk 4]
```diff
@@ -49,7 +49,12 @@
...
+
+    private static final String FAILING_FUNCTION
+            = "def handle(input_list):\n"
+            + "    assert 1 == 2\n"
+            + "    return ['echo-%s' % i for i in input_list]\n";
```
Comment (viliam-durina) [inline extensions/python/src/test/java/com/hazelcast/jet/python/PythonServiceTest.java]: This line probably isn't necessary. Also can't assertions be turned off as in java?
