### PR TITLE
Fix S3SinkTest Issue

### LINKED ISSUE #2317: com.hazelcast.jet.s3.S3SinkTest.test
_master_ (commit 82caae08a611be0db0a739fe9699dc98a5be5183)

Failed on nightly build: http://jenkins.hazelcast.com/job/jet-oss-master-nightly/162/testReport/com.hazelcast.jet.s3/S3SinkTest/test/

Stacktrace:
```
software.amazon.awssdk.services.s3.model.NoSuchKeyException: The specified key does not exist. (Service: S3, Status Code: 404, Request ID: BD11E2F39474361B)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleErrorResponse(HandleResponseStage.java:115)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleResponse(HandleResponseStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:58)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:64)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:113)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:86)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:62)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:57)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:240)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:96)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:120)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:61)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:51)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:62)
	at software.amazon.awssdk.services.s3.DefaultS3Client.getObject(DefaultS3Client.java:1601)
	at software.amazon.awssdk.services.s3.S3Client.getObject(S3Client.java:2268)
	at com.hazelcast.jet.s3.S3TestBase.lambda$null$2(S3TestBase.java:90)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.LongPipeline.reduce(LongPipeline.java:439)
	at java.util.stream.LongPipeline.sum(LongPipeline.java:397)
	at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:526)
	at com.hazelcast.jet.s3.S3TestBase.lambda$testSink$4(S3TestBase.java:93)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1356)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1458)
	at com.hazelcast.jet.s3.S3TestBase.testSink(S3TestBase.java:85)
	at com.hazelcast.jet.s3.S3TestBase.testSink(S3TestBase.java:68)
	at com.hazelcast.jet.s3.S3TestBase.testSink(S3TestBase.java:64)
	at com.hazelcast.jet.s3.S3SinkTest.test(S3SinkTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Hiccups measured while running test 'test(com.hazelcast.jet.s3.S3SinkTest):'
23:27:45, accumulated pauses: 135 ms, max pause: 18 ms, pauses over 1000 ms: 0
23:27:50, accumulated pauses: 254 ms, max pause: 104 ms, pauses over 1000 ms: 0
23:27:55, accumulated pauses: 42 ms, max pause: 9 ms, pauses over 1000 ms: 0
```

### PR DESCRIPTION
**Pull request by ufukyilmaz**
The issue here is that the test code gets the list of keys by asking the s3 server, but when it asks for the value of one of these keys in the next step, the s3 server could not find this key. We can say that seeing a key, then not seeing the same key is an eventual consistency issue in the S3 side (Note: Frantisek showed me this point and said that he also encountered this type of issue during s3 benchmarks. He can help discussions on this topic). Although they say s3 provides eventual consistency, it may not. I added a conditional wait after these key deletions because maybe the key deletions are running slowly.
I am aware that with eventual consistency guarantee, write operations may be reflected after cleanup. But we call cleanup before and after tests. In such a case, the test including these writes will fail before since these writes will not be visible in this test.

- Add a new method that suppresses exceptions in AssertTrueEventually. Use this AssertTrueEventuallyAndSuppressExceptions method in S3SinkTests. (This is somewhat controversial. Is it okay to suppress the exceptions here?)
- Use the latest versions of S3 APIs which are recommended.
- Also, add conditional wait after test cleanup which is called before and after tests.
- Change the logging level to INFO.

Checklist
- [x] Tags Set
- [x] Milestone Set

Links to issues fixed (if any):

Fixes #2317

### CODE REVIEW

**Comment by ufukyilmaz** [comment]
In the S3 tests, only the ERROR level logs are visible in jenkins. I want to change it too. I searched for a little bit but didn't find how to change it. I guess I need to edit the script that runs these tests in Jenkins.

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3357/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3357/jet-oss-pr-builder-3357.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:checkstyle (default) on project hazelcast-jet-s3: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.29 with /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder/extensions/s3/src/test/java/com/hazelcast/jet/s3/S3TestBase.java:175: Line is longer than 123 characters (found 134). [LineLength]
--------------------------
</details>
</pre>

File: extensions/s3/src/test/java/com/hazelcast/jet/s3/S3SinkTest.java [hunk 1]
```diff
@@ -51,6 +54,24 @@ public void deleteObjects() {
         if (!identifiers.isEmpty()) {
             client.deleteObjects(b -> b.bucket(bucketName).delete(d -> d.objects(identifiers)));
         }
+
+        int sleepMillis = (int) (SECONDS.toMillis(WAIT_AFTER_CLEANUP_IN_SECS) / 10);
+        long deadline = System.currentTimeMillis() + SECONDS.toMillis(WAIT_AFTER_CLEANUP_IN_SECS);
+        int keyCount;
+        while ((keyCount = client.listObjectsV2(ListObjectsV2Request
```
Comment (gurbuzali) [inline extensions/s3/src/test/java/com/hazelcast/jet/s3/S3SinkTest.java:61]: we can move this to a method for readibility and for re-use:
`client.listObjectsV2(ListObjectsV2Request.builder().bucket(bucketName).build())`

File: extensions/s3/src/test/java/com/hazelcast/jet/s3/S3TestBase.java [hunk 2]
```diff
@@ -168,6 +170,23 @@ void deleteBucket(S3Client client, String bucket) {
         }
     }
 
+    Stream<String> S3ObjectToLines(S3Object o, S3Client client, String bucketName) {
```
Comment (gurbuzali) [inline extensions/s3/src/test/java/com/hazelcast/jet/s3/S3TestBase.java:173]: start method name with lower case

File: extensions/s3/src/test/java/com/hazelcast/jet/s3/S3TestBase.java [hunk 3]
```diff
@@ -168,6 +170,23 @@ void deleteBucket(S3Client client, String bucket) {
...
+        try {
+            ResponseInputStream<GetObjectResponse> is = client.getObject(req -> req.bucket(bucketName).key(o.key()), toInputStream());
+            try (BufferedReader reader = new BufferedReader(new InputStreamReader(is, CHARSET))) {
+                // materialize the stream, since we can't read it afterwards
+                return reader.lines().collect(Collectors.toList()).stream();
+            } catch (IOException e) {
+                throw new AssertionError("Error reading file ", e);
+            }
+        } catch (NoSuchBucketException e) {
```
Comment (gurbuzali) [inline extensions/s3/src/test/java/com/hazelcast/jet/s3/S3TestBase.java:182]: the exception from the issue is `NoSuchKeyException` not `NoSuchBucketException`
I think we can use the parent `S3Exception` here

File: extensions/s3/src/test/java/com/hazelcast/jet/s3/S3TestBase.java [hunk 4]
```diff
@@ -168,6 +170,23 @@ void deleteBucket(S3Client client, String bucket) {
...
+            logger.warning("S3 side is having eventual consistency issue that it could not" +
+                    " find the key that is listed before. We ignore this issue.");
+            e.printStackTrace();
```
Comment (gurbuzali) [inline extensions/s3/src/test/java/com/hazelcast/jet/s3/S3TestBase.java:185]: you can pass the exception to the `logger.warning` as an argument instead of print stacktrace

File: extensions/s3/src/test/java/com/hazelcast/jet/s3/S3TestBase.java [hunk 5]
```diff
@@ -168,6 +170,23 @@ void deleteBucket(S3Client client, String bucket) {
         }
     }
 
+    Stream<String> S3ObjectToLines(S3Object o, S3Client client, String bucketName) {
+        try {
+            ResponseInputStream<GetObjectResponse> is = client.getObject(req -> req.bucket(bucketName).key(o.key()), toInputStream());
+            try (BufferedReader reader = new BufferedReader(new InputStreamReader(is, CHARSET))) {
```
Comment (gurbuzali) [inline extensions/s3/src/test/java/com/hazelcast/jet/s3/S3TestBase.java:176]: why copy/paste `inputStreamToLines` here ? we can just call it 
`return inputStreamToLines(client.getObject(req -> req.bucket(bucketName).key(o.key()), toInputStream()));`

**Comment by hz-highfive** [comment]
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3361/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3361/jet-oss-pr-builder-3361.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:checkstyle (default) on project hazelcast-jet-s3: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.29 with /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder_2/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder_2/extensions/s3/src/test/java/com/hazelcast/jet/s3/S3TestBase.java:176: Line is longer than 123 characters (found 134). [LineLength]
--------------------------
</details>
</pre>

**Review by gurbuzali — APPROVED** [review]
