### PR TITLE
Increase the timeout in the test that uses observable

### LINKED ISSUE #2932: com.hazelcast.jet.core.JobSerializerTest.when_serializerIsRegistered_then_itIsAvailableForLocalObservableSink
_master_ (commit a1938f1e63b36c8977848aad8b08fd1a0d316e22)

Failed on IBM JDK 8: http://jenkins.hazelcast.com/job/jet-oss-master-ibm-jdk8/335/testReport/junit/com.hazelcast.jet.core/JobSerializerTest/when_serializerIsRegistered_then_itIsAvailableForLocalObservableSink/

Stacktrace:
```
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1795)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1939)
	at com.hazelcast.jet.core.JobSerializerTest.when_serializerIsRegistered_then_itIsAvailableForLocalObservableSink(JobSerializerTest.java:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:822)
```

Standard output:
```
2021-02-28 02:44:06,239 [ INFO] [Time-limited test] [c.h.i.m.i.MetricsConfigHelper]: [LOCAL] [jet] [4.5-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
2021-02-28 02:44:06,241 [ INFO] [Time-limited test] [c.h.system]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Hazelcast Jet 4.5-SNAPSHOT (20210228 - a1938f1) starting at [127.0.0.1]:5701
2021-02-28 02:44:06,241 [ INFO] [Time-limited test] [c.h.system]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Based on Hazelcast IMDG version: 4.2.0 (20210226 - 04e9df4)
2021-02-28 02:44:06,241 [ INFO] [Time-limited test] [c.h.system]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Cluster name: jet
2021-02-28 02:44:06,241 [ INFO] [Time-limited test] [c.h.system]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] 
	o   o   o   o---o o---o o     o---o   o   o---o o-o-o        o o---o o-o-o
	|   |  / \     /  |     |     |      / \  |       |          | |       |
	o---o o---o   o   o-o   |     o     o---o o---o   |          | o-o     |
	|   | |   |  /    |     |     |     |   |     |   |      \   | |       |
	o   o o   o o---o o---o o---o o---o o   o o---o   o       o--o o---o   o
2021-02-28 02:44:06,241 [ INFO] [Time-limited test] [c.h.system]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
2021-02-28 02:44:06,244 [ INFO] [Time-limited test] [c.h.i.m.i.MetricsConfigHelper]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
2021-02-28 02:44:06,256 [ WARN] [Time-limited test] [c.h.c.CPSubsystem]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
2021-02-28 02:44:06,268 [ INFO] [Time-limited test] [c.h.j.i.JetService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Setting number of cooperative threads and default parallelism to 72
2021-02-28 02:44:06,275 [ INFO] [Time-limited test] [c.h.i.d.Diagnostics]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2021-02-28 02:44:06,275 [ INFO] [Time-limited test] [c.h.c.LifecycleService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] [127.0.0.1]:5701 is STARTING
2021-02-28 02:44:06,276 [ INFO] [Time-limited test] [c.h.i.c.ClusterService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 0bf11857-1846-4b0c-80bb-ab5463860959 this
]

2021-02-28 02:44:06,276 [DEBUG] [hz.recursing_easley.cached.thread-1] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
2021-02-28 02:44:06,276 [ INFO] [Time-limited test] [c.h.c.LifecycleService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] [127.0.0.1]:5701 is STARTED
2021-02-28 02:44:06,281 [ INFO] [Time-limited test] [c.h.s.d.i.DiscoveryService]: hz.client_9 [jet] [4.5-SNAPSHOT] [4.2-SNAPSHOT] No discovery strategy is applicable for auto-detection
2021-02-28 02:44:06,282 [ INFO] [Time-limited test] [c.h.c.i.s.ClientInvocationService]: hz.client_9 [jet] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Running with 2 response threads, dynamic=true
2021-02-28 02:44:06,283 [ INFO] [Time-limited test] [c.h.c.LifecycleService]: hz.client_9 [jet] [4.5-SNAPSHOT] [4.2-SNAPSHOT] HazelcastClient 4.2-SNAPSHOT (20210226 - 04e9df4) is STARTING
2021-02-28 02:44:06,284 [ INFO] [Time-limited test] [c.h.c.LifecycleService]: hz.client_9 [jet] [4.5-SNAPSHOT] [4.2-SNAPSHOT] HazelcastClient 4.2-SNAPSHOT (20210226 - 04e9df4) is STARTED
2021-02-28 02:44:06,285 [ INFO] [Time-limited test] [c.h.c.i.c.ClientConnectionManager]: hz.client_9 [jet] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Trying to connect to cluster: jet
2021-02-28 02:44:06,285 [ INFO] [Time-limited test] [c.h.c.i.c.ClientConnectionManager]: hz.client_9 [jet] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Trying to connect to [127.0.0.1]:5701
2021-02-28 02:44:06,285 [ INFO] [Time-limited test] [c.h.c.HazelcastClient]: Created connection to endpoint: [127.0.0.1]:5701, connection: MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=true, connectionId=1, channel=null, remoteAddress=null, lastReadTime=never, lastWriteTime=never, closedTime=never, connected server version=null}}
2021-02-28 02:44:06,286 [ INFO] [hz.recursing_easley.priority-generic-operation.thread-0] [c.h.c.i.p.t.AuthenticationMessageTask]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Received auth from MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5701, connectionId = 1}, successfully authenticated, clientUuid: 5d021832-7ae0-4ce4-b596-3960182e786c, client version: 4.2-SNAPSHOT
2021-02-28 02:44:06,287 [ INFO] [Time-limited test] [c.h.c.LifecycleService]: hz.client_9 [jet] [4.5-SNAPSHOT] [4.2-SNAPSHOT] HazelcastClient 4.2-SNAPSHOT (20210226 - 04e9df4) is CLIENT_CONNECTED
2021-02-28 02:44:06,287 [ INFO] [Time-limited test] [c.h.c.i.c.ClientConnectionManager]: hz.client_9 [jet] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Authenticated with server [127.0.0.1]:5701:0bf11857-1846-4b0c-80bb-ab5463860959, server version: 4.2-SNAPSHOT, local address: /127.0.0.1:40001
2021-02-28 02:44:06,288 [ INFO] [Time-limited test] [c.h.i.d.Diagnostics]: hz.client_9 [jet] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2021-02-28 02:44:06,290 [ INFO] [hz.client_9.event-431] [c.h.c.i.s.ClientClusterService]: hz.client_9 [jet] [4.5-SNAPSHOT] [4.2-SNAPSHOT] 

Members [1] {
	Member [127.0.0.1]:5701 - 0bf11857-1846-4b0c-80bb-ab5463860959
}

2021-02-28 02:44:06,293 [ INFO] [Time-limited test] [c.h.c.i.s.ClientStatisticsService]: Client statistics is enabled with period 5 seconds.
Started Running Test: when_serializerIsRegistered_then_itIsAvailableForLocalObservableSink
2021-02-28 02:44:06,299 [ INFO] [hz.recursing_easley.partition-operation.thread-4] [c.h.i.p.i.PartitionStateManager]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Initializing cluster partition table arrangement...
2021-02-28 02:44:06,315 [ INFO] [when_serializerIsRegistered_then_itIsAvailableForLocalObservableSink] [c.h.j.i.JetClientInstanceImpl]: hz.client_9 [jet] [4.5-SNAPSHOT] [4.2-SNAPSHOT] Starting message listener '33ad5a6d-6d35-40dc-9929-6045748acf7d/__jet.observables.observable'
2021-02-28 02:44:06,322 [DEBUG] [hz.recursing_easley.cached.thread-1] [c.h.j.i.p.Planner]: Watermarks in the pipeline will be throttled to 1000
2021-02-28 02:44:06,324 [ INFO] [hz.recursing_easley.cached.thread-1] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Starting job 05cd-e03d-8bc0-0001 based on submit request
2021-02-28 02:44:06,325 [ INFO] [hz.recursing_easley.cached.thread-1] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Didn't find any snapshot to restore for job '05cd-e03d-8bc0-0001', execution 05cd-e03d-8d40-0001
2021-02-28 02:44:06,325 [ INFO] [hz.recursing_easley.cached.thread-1] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Start executing job '05cd-e03d-8bc0-0001', execution 05cd-e03d-8d40-0001, execution graph in DOT format:
digraph DAG {
	"items" [localParallelism=1];
	"map" [localParallelism=72];
	"observableSink(observable)" [localParallelism=1];
	"items" -> "map" [queueSize=1024];
	"map" -> "observableSink(observable)" [queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
2021-02-28 02:44:06,325 [DEBUG] [hz.recursing_easley.cached.thread-1] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Building execution plan for job '05cd-e03d-8bc0-0001', execution 05cd-e03d-8d40-0001
2021-02-28 02:44:06,325 [DEBUG] [hz.recursing_easley.cached.thread-1] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Built execution plans for job '05cd-e03d-8bc0-0001', execution 05cd-e03d-8d40-0001
2021-02-28 02:44:06,326 [DEBUG] [hz.recursing_easley.cached.thread-1] [c.h.j.i.o.InitExecutionOperation]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Initializing execution plan for job 05cd-e03d-8bc0-0001, execution 05cd-e03d-8d40-0001 from [127.0.0.1]:5701
2021-02-28 02:44:06,329 [ INFO] [hz.recursing_easley.cached.thread-1] [c.h.j.i.JobExecutionService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Execution plan for jobId=05cd-e03d-8bc0-0001, jobName='05cd-e03d-8bc0-0001', executionId=05cd-e03d-8d40-0001 initialized
2021-02-28 02:44:06,329 [DEBUG] [hz.recursing_easley.cached.thread-1] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Init of job '05cd-e03d-8bc0-0001', execution 05cd-e03d-8d40-0001 was successful
2021-02-28 02:44:06,329 [DEBUG] [hz.recursing_easley.cached.thread-1] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Executing job '05cd-e03d-8bc0-0001', execution 05cd-e03d-8d40-0001
2021-02-28 02:44:06,329 [ INFO] [hz.recursing_easley.cached.thread-1] [c.h.j.i.JobExecutionService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Start execution of job '05cd-e03d-8bc0-0001', execution 05cd-e03d-8d40-0001 from coordinator [127.0.0.1]:5701
2021-02-28 02:44:06,338 [DEBUG] [hz.recursing_easley.jet.cooperative.thread-53] [c.h.j.i.JobExecutionService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Execution of job '05cd-e03d-8bc0-0001', execution 05cd-e03d-8d40-0001 completed
2021-02-28 02:44:06,338 [DEBUG] [ForkJoinPool.commonPool-worker-87] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Execution of job '05cd-e03d-8bc0-0001', execution 05cd-e03d-8d40-0001 was successful
2021-02-28 02:44:06,338 [DEBUG] [hz.recursing_easley.cached.thread-23] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Sending CompleteExecutionOperation for job '05cd-e03d-8bc0-0001', execution 05cd-e03d-8d40-0001
2021-02-28 02:44:06,338 [DEBUG] [hz.recursing_easley.cached.thread-23] [c.h.j.i.o.CompleteExecutionOperation]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Completing execution 05cd-e03d-8d40-0001 from caller [127.0.0.1]:5701, error=null
2021-02-28 02:44:06,339 [DEBUG] [hz.recursing_easley.cached.thread-23] [c.h.j.i.JobExecutionService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Completed execution of job '05cd-e03d-8bc0-0001', execution 05cd-e03d-8d40-0001
2021-02-28 02:44:06,339 [ INFO] [hz.recursing_easley.cached.thread-23] [c.h.j.i.MasterJobContext]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Execution of job '05cd-e03d-8bc0-0001', execution 05cd-e03d-8d40-0001 completed successfully
	Start time: 2021-02-28T02:44:06.324
	Duration: 00:00:00.015
	To see additional job metrics enable JobConfig.storeMetricsAfterJobCompletion
2021-02-28 02:44:06,339 [DEBUG] [hz.recursing_easley.cached.thread-23] [c.h.j.i.JobCoordinationService]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] job '05cd-e03d-8bc0-0001', execution 05cd-e03d-8d40-0001 is completed
2021-02-28 02:44:06,379 [DEBUG] [hz.recursing_easley.cached.thread-23] [c.h.j.i.JobRepository]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Job cleanup took 1ms
2021-02-28 02:44:11,382 [DEBUG] [hz.recursing_easley.cached.thread-38] [c.h.j.i.JobRepository]: [127.0.0.1]:5701 [jet] [4.5-SNAPSHOT] Job cleanup took 1ms
2021-02-28 02:44:11,420 [ INFO] [Time-limited test] [c.h.j.SimpleTestInClusterSupport]: Ditching 1 jobs in SimpleTestInClusterSupport.@After: [05cd-e03d-8bc0-0001]
2021-02-28 02:44:11,421 [ INFO] [Time-limited test] [c.h.j.SimpleTestInClusterSupport]: Destroying 7 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__jet.executionRecords, hz:impl:mapService/__jet.exportedSnapshotsCache, hz:impl:mapService/__jet.results, hz:impl:mapService/__jet.results.metrics, hz:impl:mapService/__jet.records, hz:impl:flakeIdGeneratorService/__jet.ids, hz:impl:ringbufferService/__jet.observables.observable]
BuildInfo right after when_serializerIsRegistered_then_itIsAvailableForLocalObservableSink(com.hazelcast.jet.core.JobSerializerTest): BuildInfo{version='4.2-SNAPSHOT', build='20210226', buildNumber=20210226, revision=04e9df4, enterprise=false, serializationVersion=1, jet=JetBuildInfo{version='4.5-SNAPSHOT', build='20210228', revision='a1938f1'}}
Hiccups measured while running test 'when_serializerIsRegistered_then_itIsAvailableForLocalObservableSink(com.hazelcast.jet.core.JobSerializerTest):'
02:44:05, accumulated pauses: 59 ms, max pause: 10 ms, pauses over 1000 ms: 0
02:44:10, accumulated pauses: 24 ms, max pause: 17 ms, pauses over 1000 ms: 0
```

### PR DESCRIPTION
**Pull request by ufukyilmaz**
I increased the timeout in this test to make sure something went wrong
when this test fails. This test won't take long when it passes anyway.

Also, added missing Nonnull annotation

Checklist:
- [x] Labels and Milestone set

### CODE REVIEW

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobSerializerTest.java [hunk 1]
```diff
@@ -192,14 +193,15 @@ public void when_serializerIsRegistered_then_itIsAvailableForLocalObservableSink
         pipeline.readFrom(TestSources.items(1, 2))
                 .map(Value::new)
                 .writeTo(Sinks.observable(OBSERVABLE_NAME));
+        long timeout = 120;
```
Comment (gierlachg) [inline hazelcast-jet-core/src/test/java/com/hazelcast/jet/core/JobSerializerTest.java:196]: Why not to simply inline it? Why 120?

**Review by gierlachg — APPROVED** [review]
