### PR TITLE
Fix intermittent test failure in StreamSourceStageTest

### LINKED ISSUE #1591: com.hazelcast.jet.pipeline.StreamSourceStageTest.test_sourceJournal_withoutTimestamps
http://jenkins.hazelcast.com/job/jet-oss-master-sonar-nightly/226/testReport/junit/com.hazelcast.jet.pipeline/StreamSourceStageTest/test_sourceJournal_withoutTimestamps/

Stacktrace:
```
Stacktrace
java.lang.AssertionError: expected:<[2, 3]> but was:<[3]>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.jet.pipeline.StreamSourceStageTestBase.lambda$test$3(StreamSourceStageTestBase.java:115)
	at com.hazelcast.jet.core.JetTestSupport$1.run(JetTestSupport.java:201)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1310)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1327)
	at com.hazelcast.jet.core.JetTestSupport.assertTrueEventually(JetTestSupport.java:162)
	at com.hazelcast.jet.pipeline.StreamSourceStageTestBase.test(StreamSourceStageTestBase.java:116)
	at com.hazelcast.jet.pipeline.StreamSourceStageTest.test_sourceJournal_withoutTimestamps(StreamSourceStageTest.java:114)
```

Standard output:
```
Error Message
expected:<[2, 3]> but was:<[3]>
```

### PR DESCRIPTION
**Pull request by cangencer**
In StreamSourceStageTestBase the WatermarkCollector
would only process one wm and then perpetually return false
since it was trying to emit it. Tests were only passing because
each watermarks was going to a different processor.

Fixes #1591

### CODE REVIEW

File: hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamSourceStageTestBase.java [hunk 1]
```diff
@@ -104,15 +105,22 @@ protected void test(
...
         stageWithTimestamps
                 .peek()
+                // we use a tumbling window of size 1 to force maximum watermark gap to be 1
+                // this should be removed once https://github.com/hazelcast/hazelcast-jet/issues/1365
+                // fixed. local parallelism should be 1 to make sure watermarks don't get
+                // coalesced
                 .window(WindowDefinition.tumbling(1))
-                .aggregate(counting())
+                .aggregate(AggregateOperations.counting())
+                .setLocalParallelism(1)
```
Comment (viliam-durina) [inline hazelcast-jet-core/src/test/java/com/hazelcast/jet/pipeline/StreamSourceStageTestBase.java]: This isn't needed.
